export type Airport = {
  iata: string;
  name: string;
  city: string;
  country: string;
};

export const AIRPORTS: Airport[] = [
  { iata: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "Indonesia" },
  { iata: "SUB", name: "Juanda International", city: "Surabaya", country: "Indonesia" },
  { iata: "DPS", name: "Ngurah Rai International", city: "Bali/Denpasar", country: "Indonesia" },
  { iata: "UPG", name: "Sultan Hasanuddin International", city: "Makassar", country: "Indonesia" },
  { iata: "KNO", name: "Kualanamu International", city: "Medan", country: "Indonesia" },
  { iata: "BPN", name: "Sultan Aji Muhammad Sulaiman", city: "Balikpapan", country: "Indonesia" },
  { iata: "PLM", name: "Sultan Mahmud Badaruddin II", city: "Palembang", country: "Indonesia" },
  { iata: "MDC", name: "Sam Ratulangi International", city: "Manado", country: "Indonesia" },
  { iata: "PKU", name: "Sultan Syarif Kasim II", city: "Pekanbaru", country: "Indonesia" },
  { iata: "PNK", name: "Supadio International", city: "Pontianak", country: "Indonesia" },
  { iata: "AMQ", name: "Pattimura International", city: "Ambon", country: "Indonesia" },
  { iata: "TIM", name: "Moses Kilangin International", city: "Timika", country: "Indonesia" },
  { iata: "BIK", name: "Frans Kaisiepo International", city: "Biak", country: "Indonesia" },
  { iata: "MLG", name: "Abdul Rachman Saleh", city: "Malang", country: "Indonesia" },
  { iata: "JOG", name: "Adisutjipto International", city: "Yogyakarta", country: "Indonesia" },
  { iata: "SRG", name: "Ahmad Yani International", city: "Semarang", country: "Indonesia" },
  { iata: "PDG", name: "Minangkabau International", city: "Padang", country: "Indonesia" },
  { iata: "BTJ", name: "Sultan Iskandar Muda", city: "Banda Aceh", country: "Indonesia" },
  { iata: "LOP", name: "Lombok International", city: "Lombok", country: "Indonesia" },
  { iata: "KOE", name: "El Tari International", city: "Kupang", country: "Indonesia" },
  { iata: "SIN", name: "Changi International", city: "Singapore", country: "Singapore" },
  { iata: "KUL", name: "Kuala Lumpur International (KLIA)", city: "Kuala Lumpur", country: "Malaysia" },
  { iata: "PEN", name: "Penang International", city: "Penang", country: "Malaysia" },
  { iata: "KCH", name: "Kuching International", city: "Kuching", country: "Malaysia" },
  { iata: "BKI", name: "Kota Kinabalu International", city: "Kota Kinabalu", country: "Malaysia" },
  { iata: "BKK", name: "Suvarnabhumi International", city: "Bangkok", country: "Thailand" },
  { iata: "DMK", name: "Don Mueang International", city: "Bangkok", country: "Thailand" },
  { iata: "HKT", name: "Phuket International", city: "Phuket", country: "Thailand" },
  { iata: "CNX", name: "Chiang Mai International", city: "Chiang Mai", country: "Thailand" },
  { iata: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines" },
  { iata: "CEB", name: "Mactan-Cebu International", city: "Cebu", country: "Philippines" },
  { iata: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "Vietnam" },
  { iata: "HAN", name: "Noi Bai International", city: "Hanoi", country: "Vietnam" },
  { iata: "DAD", name: "Da Nang International", city: "Da Nang", country: "Vietnam" },
  { iata: "RGN", name: "Yangon International", city: "Yangon", country: "Myanmar" },
  { iata: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "Cambodia" },
  { iata: "VTE", name: "Wattay International", city: "Vientiane", country: "Laos" },
  { iata: "BWN", name: "Brunei International", city: "Bandar Seri Begawan", country: "Brunei" },
  { iata: "CMB", name: "Bandaranaike International", city: "Colombo", country: "Sri Lanka" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India" },
  { iata: "DEL", name: "Indira Gandhi International", city: "New Delhi", country: "India" },
  { iata: "BLR", name: "Kempegowda International", city: "Bengaluru", country: "India" },
  { iata: "MAA", name: "Chennai International", city: "Chennai", country: "India" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "India" },
  { iata: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "India" },
  { iata: "COK", name: "Cochin International", city: "Kochi", country: "India" },
  { iata: "DAC", name: "Hazrat Shahjalal International", city: "Dhaka", country: "Bangladesh" },
  { iata: "KTM", name: "Tribhuvan International", city: "Kathmandu", country: "Nepal" },
  { iata: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "Hong Kong" },
  { iata: "PVG", name: "Pudong International", city: "Shanghai", country: "China" },
  { iata: "SHA", name: "Hongqiao International", city: "Shanghai", country: "China" },
  { iata: "PEK", name: "Beijing Capital International", city: "Beijing", country: "China" },
  { iata: "PKX", name: "Beijing Daxing International", city: "Beijing", country: "China" },
  { iata: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "China" },
  { iata: "SZX", name: "Shenzhen Bao'an International", city: "Shenzhen", country: "China" },
  { iata: "CTU", name: "Chengdu Tianfu International", city: "Chengdu", country: "China" },
  { iata: "CKG", name: "Chongqing Jiangbei International", city: "Chongqing", country: "China" },
  { iata: "XIY", name: "Xi'an Xianyang International", city: "Xi'an", country: "China" },
  { iata: "WUH", name: "Wuhan Tianhe International", city: "Wuhan", country: "China" },
  { iata: "NKG", name: "Nanjing Lukou International", city: "Nanjing", country: "China" },
  { iata: "HGH", name: "Hangzhou Xiaoshan International", city: "Hangzhou", country: "China" },
  { iata: "XMN", name: "Xiamen Gaoqi International", city: "Xiamen", country: "China" },
  { iata: "KMG", name: "Kunming Changshui International", city: "Kunming", country: "China" },
  { iata: "TAO", name: "Qingdao Jiaodong International", city: "Qingdao", country: "China" },
  { iata: "TNA", name: "Jinan Yaoqiang International", city: "Jinan", country: "China" },
  { iata: "ICN", name: "Incheon International", city: "Seoul", country: "South Korea" },
  { iata: "GMP", name: "Gimpo International", city: "Seoul", country: "South Korea" },
  { iata: "PUS", name: "Gimhae International", city: "Busan", country: "South Korea" },
  { iata: "NRT", name: "Narita International", city: "Tokyo", country: "Japan" },
  { iata: "HND", name: "Haneda International", city: "Tokyo", country: "Japan" },
  { iata: "KIX", name: "Kansai International", city: "Osaka", country: "Japan" },
  { iata: "NGO", name: "Chubu Centrair International", city: "Nagoya", country: "Japan" },
  { iata: "FUK", name: "Fukuoka International", city: "Fukuoka", country: "Japan" },
  { iata: "CTS", name: "New Chitose International", city: "Sapporo", country: "Japan" },
  { iata: "TPE", name: "Taoyuan International", city: "Taipei", country: "Taiwan" },
  { iata: "TSA", name: "Songshan Airport", city: "Taipei", country: "Taiwan" },
  { iata: "KHH", name: "Kaohsiung International", city: "Kaohsiung", country: "Taiwan" },
  { iata: "DXB", name: "Dubai International", city: "Dubai", country: "UAE" },
  { iata: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "UAE" },
  { iata: "SHJ", name: "Sharjah International", city: "Sharjah", country: "UAE" },
  { iata: "DOH", name: "Hamad International", city: "Doha", country: "Qatar" },
  { iata: "BAH", name: "Bahrain International", city: "Manama", country: "Bahrain" },
  { iata: "KWI", name: "Kuwait International", city: "Kuwait City", country: "Kuwait" },
  { iata: "MCT", name: "Muscat International", city: "Muscat", country: "Oman" },
  { iata: "RUH", name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia" },
  { iata: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia" },
  { iata: "DMM", name: "King Fahd International", city: "Dammam", country: "Saudi Arabia" },
  { iata: "AMM", name: "Queen Alia International", city: "Amman", country: "Jordan" },
  { iata: "BEY", name: "Rafic Hariri International", city: "Beirut", country: "Lebanon" },
  { iata: "TLV", name: "Ben Gurion International", city: "Tel Aviv", country: "Israel" },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  { iata: "SAW", name: "Sabiha Gökçen International", city: "Istanbul", country: "Turkey" },
  { iata: "ESB", name: "Ankara Esenboğa International", city: "Ankara", country: "Turkey" },
  { iata: "AYT", name: "Antalya International", city: "Antalya", country: "Turkey" },
  { iata: "TBZ", name: "Tabriz International", city: "Tabriz", country: "Iran" },
  { iata: "IKA", name: "Imam Khomeini International", city: "Tehran", country: "Iran" },
  { iata: "KBL", name: "Hamid Karzai International", city: "Kabul", country: "Afghanistan" },
  { iata: "KHI", name: "Jinnah International", city: "Karachi", country: "Pakistan" },
  { iata: "LHE", name: "Allama Iqbal International", city: "Lahore", country: "Pakistan" },
  { iata: "ISB", name: "Islamabad International", city: "Islamabad", country: "Pakistan" },
  { iata: "LHR", name: "Heathrow International", city: "London", country: "United Kingdom" },
  { iata: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom" },
  { iata: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom" },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom" },
  { iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom" },
  { iata: "CDG", name: "Charles de Gaulle International", city: "Paris", country: "France" },
  { iata: "ORY", name: "Orly Airport", city: "Paris", country: "France" },
  { iata: "LYS", name: "Lyon–Saint-Exupéry International", city: "Lyon", country: "France" },
  { iata: "NCE", name: "Nice Côte d'Azur International", city: "Nice", country: "France" },
  { iata: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France" },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { iata: "MUC", name: "Munich International", city: "Munich", country: "Germany" },
  { iata: "DUS", name: "Düsseldorf International", city: "Düsseldorf", country: "Germany" },
  { iata: "TXL", name: "Berlin Brandenburg International", city: "Berlin", country: "Germany" },
  { iata: "BER", name: "Berlin Brandenburg International", city: "Berlin", country: "Germany" },
  { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
  { iata: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany" },
  { iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
  { iata: "LGG", name: "Liège Airport", city: "Liège", country: "Belgium" },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { iata: "GVA", name: "Geneva International", city: "Geneva", country: "Switzerland" },
  { iata: "VIE", name: "Vienna International", city: "Vienna", country: "Austria" },
  { iata: "FCO", name: "Leonardo da Vinci International", city: "Rome", country: "Italy" },
  { iata: "MXP", name: "Milano Malpensa International", city: "Milan", country: "Italy" },
  { iata: "LIN", name: "Milan Linate Airport", city: "Milan", country: "Italy" },
  { iata: "MAD", name: "Adolfo Suárez Madrid–Barajas", city: "Madrid", country: "Spain" },
  { iata: "BCN", name: "Barcelona–El Prat International", city: "Barcelona", country: "Spain" },
  { iata: "LIS", name: "Humberto Delgado International", city: "Lisbon", country: "Portugal" },
  { iata: "OPO", name: "Francisco Sá Carneiro International", city: "Porto", country: "Portugal" },
  { iata: "ATH", name: "Athens International", city: "Athens", country: "Greece" },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
  { iata: "BUD", name: "Budapest Liszt Ferenc International", city: "Budapest", country: "Hungary" },
  { iata: "OTP", name: "Henri Coandă International", city: "Bucharest", country: "Romania" },
  { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria" },
  { iata: "SVO", name: "Sheremetyevo International", city: "Moscow", country: "Russia" },
  { iata: "DME", name: "Domodedovo International", city: "Moscow", country: "Russia" },
  { iata: "LED", name: "Pulkovo Airport", city: "St. Petersburg", country: "Russia" },
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "USA" },
  { iata: "EWR", name: "Newark Liberty International", city: "New York/Newark", country: "USA" },
  { iata: "LGA", name: "LaGuardia Airport", city: "New York", country: "USA" },
  { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "USA" },
  { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "USA" },
  { iata: "MDW", name: "Chicago Midway International", city: "Chicago", country: "USA" },
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "USA" },
  { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "USA" },
  { iata: "MIA", name: "Miami International", city: "Miami", country: "USA" },
  { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "USA" },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "USA" },
  { iata: "DEN", name: "Denver International", city: "Denver", country: "USA" },
  { iata: "BOS", name: "Logan International", city: "Boston", country: "USA" },
  { iata: "IAD", name: "Dulles International", city: "Washington D.C.", country: "USA" },
  { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington D.C.", country: "USA" },
  { iata: "HOU", name: "William P. Hobby Airport", city: "Houston", country: "USA" },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "USA" },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "USA" },
  { iata: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "USA" },
  { iata: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "USA" },
  { iata: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "USA" },
  { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "USA" },
  { iata: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "USA" },
  { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "USA" },
  { iata: "PDX", name: "Portland International", city: "Portland", country: "USA" },
  { iata: "SAN", name: "San Diego International", city: "San Diego", country: "USA" },
  { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "USA" },
  { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "USA" },
  { iata: "MEM", name: "Memphis International", city: "Memphis", country: "USA" },
  { iata: "CVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", country: "USA" },
  { iata: "IND", name: "Indianapolis International", city: "Indianapolis", country: "USA" },
  { iata: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "Canada" },
  { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada" },
  { iata: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "Canada" },
  { iata: "YYC", name: "Calgary International", city: "Calgary", country: "Canada" },
  { iata: "MEX", name: "Benito Juárez International", city: "Mexico City", country: "Mexico" },
  { iata: "GDL", name: "Miguel Hidalgo y Costilla International", city: "Guadalajara", country: "Mexico" },
  { iata: "CUN", name: "Cancún International", city: "Cancún", country: "Mexico" },
  { iata: "GRU", name: "São Paulo/Guarulhos International", city: "São Paulo", country: "Brazil" },
  { iata: "CGH", name: "São Paulo/Congonhas Airport", city: "São Paulo", country: "Brazil" },
  { iata: "GIG", name: "Rio de Janeiro/Galeão International", city: "Rio de Janeiro", country: "Brazil" },
  { iata: "BSB", name: "Brasília International", city: "Brasília", country: "Brazil" },
  { iata: "SSA", name: "Luís Eduardo Magalhães International", city: "Salvador", country: "Brazil" },
  { iata: "BOG", name: "El Dorado International", city: "Bogotá", country: "Colombia" },
  { iata: "LIM", name: "Jorge Chávez International", city: "Lima", country: "Peru" },
  { iata: "SCL", name: "Arturo Merino Benítez International", city: "Santiago", country: "Chile" },
  { iata: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "Argentina" },
  { iata: "AEP", name: "Jorge Newbery Airfield", city: "Buenos Aires", country: "Argentina" },
  { iata: "MVD", name: "Carrasco International", city: "Montevideo", country: "Uruguay" },
  { iata: "ASU", name: "Silvio Pettirossi International", city: "Asunción", country: "Paraguay" },
  { iata: "CAI", name: "Cairo International", city: "Cairo", country: "Egypt" },
  { iata: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "Algeria" },
  { iata: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco" },
  { iata: "TUN", name: "Tunis-Carthage International", city: "Tunis", country: "Tunisia" },
  { iata: "TIP", name: "Mitiga International", city: "Tripoli", country: "Libya" },
  { iata: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya" },
  { iata: "ADD", name: "Bole International", city: "Addis Ababa", country: "Ethiopia" },
  { iata: "LOS", name: "Murtala Muhammed International", city: "Lagos", country: "Nigeria" },
  { iata: "ABV", name: "Nnamdi Azikiwe International", city: "Abuja", country: "Nigeria" },
  { iata: "ACC", name: "Kotoka International", city: "Accra", country: "Ghana" },
  { iata: "DAK", name: "Blaise Diagne International", city: "Dakar", country: "Senegal" },
  { iata: "DKR", name: "Léopold Sédar Senghor International", city: "Dakar", country: "Senegal" },
  { iata: "JNB", name: "O. R. Tambo International", city: "Johannesburg", country: "South Africa" },
  { iata: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa" },
  { iata: "DUR", name: "King Shaka International", city: "Durban", country: "South Africa" },
  { iata: "EBB", name: "Entebbe International", city: "Kampala", country: "Uganda" },
  { iata: "DAR", name: "Julius Nyerere International", city: "Dar es Salaam", country: "Tanzania" },
  { iata: "SYD", name: "Sydney Kingsford Smith International", city: "Sydney", country: "Australia" },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  { iata: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { iata: "CHC", name: "Christchurch International", city: "Christchurch", country: "New Zealand" },
  { iata: "WLG", name: "Wellington International", city: "Wellington", country: "New Zealand" },
  { iata: "NAN", name: "Nadi International", city: "Nadi", country: "Fiji" },
  { iata: "PPT", name: "Faa'a International", city: "Papeete", country: "French Polynesia" },
  { iata: "GUM", name: "Antonio B. Won Pat International", city: "Hagåtña", country: "Guam" },
  { iata: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "Finland" },
  { iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
  { iata: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "Norway" },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { iata: "KEF", name: "Keflavik International", city: "Reykjavik", country: "Iceland" },
  { iata: "MLA", name: "Malta International", city: "Valletta", country: "Malta" },
  { iata: "SKG", name: "Thessaloniki International", city: "Thessaloniki", country: "Greece" },
  { iata: "LCA", name: "Larnaca International", city: "Larnaca", country: "Cyprus" },
  { iata: "TBS", name: "Tbilisi International", city: "Tbilisi", country: "Georgia" },
  { iata: "EVN", name: "Zvartnots International", city: "Yerevan", country: "Armenia" },
  { iata: "GYD", name: "Heydar Aliyev International", city: "Baku", country: "Azerbaijan" },
  { iata: "NUC", name: "Almaty International", city: "Almaty", country: "Kazakhstan" },
  { iata: "ALA", name: "Almaty International", city: "Almaty", country: "Kazakhstan" },
  { iata: "TSE", name: "Nursultan Nazarbayev International", city: "Nursultan", country: "Kazakhstan" },
  { iata: "TAS", name: "Tashkent International", city: "Tashkent", country: "Uzbekistan" },
  { iata: "ULN", name: "Chinggis Khaan International", city: "Ulaanbaatar", country: "Mongolia" },
  { iata: "VVO", name: "Vladivostok International", city: "Vladivostok", country: "Russia" },
  { iata: "OVB", name: "Novosibirsk Tolmachevo Airport", city: "Novosibirsk", country: "Russia" },
  { iata: "BHQ", name: "Broken Hill Airport", city: "Broken Hill", country: "Australia" },
  { iata: "NOU", name: "La Tontouta International", city: "Nouméa", country: "New Caledonia" },
];

export function searchAirports(query: string): Airport[] {
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase().trim();
  const exact = AIRPORTS.filter((a) => a.iata.startsWith(q));
  const byCity = AIRPORTS.filter(
    (a) => !a.iata.startsWith(q) && a.city.toUpperCase().includes(q)
  );
  const byName = AIRPORTS.filter(
    (a) =>
      !a.iata.startsWith(q) &&
      !a.city.toUpperCase().includes(q) &&
      a.name.toUpperCase().includes(q)
  );
  return [...exact, ...byCity, ...byName].slice(0, 10);
}
