import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import ecommerceRouter from "./ecommerce";
import tradingRouter from "./trading";
import logisticsRouter from "./logistics";
import freightRouter from "./freight";
import posRouter from "./pos";
import salesRouter from "./sales";
import purchaseRouter from "./purchase";
import reportsRouter from "./reports";
import paymentsRouter from "./payments";
import accountingRouter from "./accounting";
import storageRouter from "./storage";
import correspondencesRouter from "./correspondences";
import emailCorrespondencesRouter from "./emailCorrespondences";
import scanDocumentRouter from "./scanDocument";
import expensesRouter from "./expenses";
import portalRouter from "./portal";
import { logisticOrdersRouter } from "./logisticOrders";
import { logisticRfqRouter } from "./logisticRfq";
import settingsRouter from "./settings";
import { driverRouter, driversAdminRouter } from "./driver";
import webhooksRouter from "./webhooks";
import { aiAgentRouter } from "./aiAgent";
import { portalProductOrdersRouter } from "./portalProductOrders";
import geocodeRouter from "./geocode";
import { whatsappRouter } from "./whatsapp";
import { vendorResponseRouter } from "./vendorResponse";
import mediaRouter from "./media";
import posKasirRouter from "./posKasir";
import posInventoryRouter from "./posInventory";
import warehouseRouter from "./warehouse";
import inventoryReceiveRouter from "./inventoryReceive";
import inventoryStockRouter from "./inventoryStock";
import inventoryMainRouter from "./inventoryMain";
import customRolesRouter from "./customRoles";
import thaiTeaSuppliesRouter from "./thaiTeaSupplies";
import purchaseWorkflowRouter from "./purchaseWorkflow";
import uomRouter from "./uom";
import orgRouter from "./org";
import approvalWorkflowRouter from "./approvalWorkflow";
import approvalRulesRouter from "./approvalRules";
import productBomRouter from "./productBom";
import auditLogRouter from "./auditLog";
import { sportCenterRouter, sportCenterPublicRouter } from "./sportCenter";
import { sportCenterAdminRouter } from "./sportCenterAdmin";
import navPreferencesRouter from "./navPreferences";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users", usersRouter);
router.use("/dashboard", dashboardRouter);
router.use("/ecommerce", ecommerceRouter);
router.use("/trading", tradingRouter);
router.use("/logistics", logisticsRouter);
router.use("/logistics", freightRouter);
router.use("/pos", posRouter);
router.use("/sales", salesRouter);
router.use("/purchase", purchaseRouter);
router.use("/reports", reportsRouter);
router.use("/payments", paymentsRouter);
router.use("/accounting", accountingRouter);
router.use("/correspondences", correspondencesRouter);
router.use("/email-correspondences", emailCorrespondencesRouter);
router.use("/scan-document", scanDocumentRouter);
router.use("/expenses", expensesRouter);
router.use("/portal", portalRouter);
router.use("/logistic/orders", logisticRfqRouter);
router.use("/logistic/orders", logisticOrdersRouter);
router.use("/settings", settingsRouter);
router.use("/driver", driverRouter);
router.use("/drivers", driversAdminRouter);
router.use(storageRouter);
router.use(webhooksRouter);
router.use("/ai-agent", aiAgentRouter);
router.use("/portal-product", portalProductOrdersRouter);
router.use(geocodeRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/vendor-response", vendorResponseRouter);
router.use("/media", mediaRouter);
router.use("/pos-kasir", posKasirRouter);
router.use("/pos-inventory", posInventoryRouter);
router.use("/warehouse", warehouseRouter);
router.use("/inventory", inventoryMainRouter);
router.use("/inventory/receive", inventoryReceiveRouter);
router.use("/inventory/stock", inventoryStockRouter);
router.use("/inventory/warehouses", inventoryStockRouter);
router.use("/custom-roles", customRolesRouter);
router.use("/thai-tea", thaiTeaSuppliesRouter);
router.use("/purchase-workflow", purchaseWorkflowRouter);
router.use("/uom", uomRouter);
router.use("/org", orgRouter);
router.use("/approvals", approvalWorkflowRouter);
router.use("/approval-rules", approvalRulesRouter);
router.use("/bom", productBomRouter);
router.use("/audit-logs", auditLogRouter);
router.use("/sport-center", sportCenterPublicRouter);
router.use("/sport-center/bookings", sportCenterRouter);
router.use("/sport-center/admin", sportCenterAdminRouter);
router.use("/notifications", notificationsRouter);
router.use("/nav-preferences", navPreferencesRouter);
export default router;
