import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import ecommerceRouter from "./ecommerce";
import tradingRouter from "./trading";
import logisticsRouter from "./logistics";
import freightRouter from "./freight";
import posRouter from "./pos";
import salesRouter from "./sales";
import purchaseRouter from "./purchase";
import reportsRouter from "./reports";
import paymentsRouter from "./payments";
import accountingRouter from "./accounting";
import storageRouter from "./storage";
import correspondencesRouter from "./correspondences";
import emailCorrespondencesRouter from "./emailCorrespondences";
import scanDocumentRouter from "./scanDocument";
import expensesRouter from "./expenses";
import portalRouter from "./portal";
import { logisticOrdersRouter } from "./logisticOrders";
import { logisticRfqRouter } from "./logisticRfq";
import settingsRouter from "./settings";
import { driverRouter, driversAdminRouter } from "./driver";
import webhooksRouter from "./webhooks";
import { aiAgentRouter } from "./aiAgent";
import { portalProductOrdersRouter } from "./portalProductOrders";
import geocodeRouter from "./geocode";
import { whatsappRouter } from "./whatsapp";
import { vendorResponseRouter } from "./vendorResponse";
import mediaRouter from "./media";
import posKasirRouter from "./posKasir";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users", usersRouter);
router.use("/dashboard", dashboardRouter);
router.use("/ecommerce", ecommerceRouter);
router.use("/trading", tradingRouter);
router.use("/logistics", logisticsRouter);
router.use("/logistics", freightRouter);
router.use("/pos", posRouter);
router.use("/sales", salesRouter);
router.use("/purchase", purchaseRouter);
router.use("/reports", reportsRouter);
router.use("/payments", paymentsRouter);
router.use("/accounting", accountingRouter);
router.use("/correspondences", correspondencesRouter);
router.use("/email-correspondences", emailCorrespondencesRouter);
router.use("/scan-document", scanDocumentRouter);
router.use("/expenses", expensesRouter);
router.use("/portal", portalRouter);
router.use("/logistic/orders", logisticRfqRouter);
router.use("/logistic/orders", logisticOrdersRouter);
router.use("/settings", settingsRouter);
router.use("/driver", driverRouter);
router.use("/drivers", driversAdminRouter);
router.use(storageRouter);
router.use(webhooksRouter);
router.use("/ai-agent", aiAgentRouter);
router.use("/portal-product", portalProductOrdersRouter);
router.use(geocodeRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/vendor-response", vendorResponseRouter);
router.use("/media", mediaRouter);
router.use("/pos-kasir", posKasirRouter);
export default router;
