import React from "react";
import { Switch, Route } from "wouter";
import NotFound from "@/pages/not-found";
import DashboardPage from "@/pages/dashboard";
import EcommercePage from "@/pages/ecommerce";
import TradingPage from "@/pages/trading";
import LogisticsPage from "@/pages/logistics";
import LogisticsFreightPage from "@/pages/logistics-freight";
import LogisticsFreightEditorPage from "@/pages/logistics-freight-editor";
import LogisticsFreightDetailPage from "@/pages/logistics-freight-detail";
import LogisticsFreightBLPage from "@/pages/logistics-freight-bl";
import LogisticsPortalOrdersPage from "@/pages/logistics-portal-orders";
import LogisticsPortalOrderDetailPage from "@/pages/logistics-portal-order-detail";
import LogisticsDriversPage from "@/pages/logistics-drivers";
import LogisticsDriverPerformancePage from "@/pages/logistics-driver-performance";
import LogisticsVendorsPage from "@/pages/logistics-vendors";
import PosPage from "@/pages/pos";
import PosBranchesPage from "@/pages/pos-branches";
import PosWarehousesPage from "@/pages/pos-warehouses";
import PosRacksPage from "@/pages/pos-racks";
import PosInventoryItemsPage from "@/pages/pos-inventory-items";
import PosInventoryStocksPage from "@/pages/pos-inventory-stocks";
import PosRecipesPage from "@/pages/pos-recipes";
import ProductItemsPage from "@/pages/products/items";
import ProductRecipesPage from "@/pages/products/recipes";
import PosStockTransfersPage from "@/pages/pos-stock-transfers";
import PosStockReturnsPage from "@/pages/pos-stock-returns";
import PosStockLossesPage from "@/pages/pos-stock-losses";
import PosStockOpnamePage from "@/pages/pos-stock-opname";
import PosStockMutationsPage from "@/pages/pos-stock-mutations";
import PosQrGeneratorPage from "@/pages/pos-qr-generator";
import PosQrScannerPage from "@/pages/pos-qr-scanner";
import PosInventoryDashboardPage from "@/pages/pos-inventory-dashboard";
import SettingsPage from "@/pages/settings";
import AiChatbotSettingsPage from "@/pages/ai-chatbot-settings";
import AiScanSettingsPage from "@/pages/ai-scan-settings";
import UomPage from "@/pages/settings/uom";
import UsersPage from "@/pages/users";
import WelcomePage from "@/pages/welcome";
import SalesDashboardPage from "@/pages/sales/dashboard";
import SalesDocumentsListPage from "@/pages/sales/documents-list";
import SalesDocumentEditorPage from "@/pages/sales/quotation-editor";
import AiDraftsPage from "@/pages/sales/ai-drafts";
import CustomersPage from "@/pages/sales/customers";
import SalesInvoicesPage from "@/pages/sales/invoices";
import SalesItemsPage from "@/pages/sales/items";
import PurchaseDashboardPage from "@/pages/purchase/dashboard";
import PurchaseDocumentsListPage from "@/pages/purchase/documents-list";
import PurchaseDocumentEditorPage from "@/pages/purchase/rfq-editor";
import PurchaseRequestListPage from "@/pages/purchase/pr-list";
import PurchaseRequestEditorPage from "@/pages/purchase/pr-editor";
import VendorsPage from "@/pages/purchase/vendors";
import VendorDetailPage from "@/pages/purchase/vendor-detail";
import PurchaseBillsPage from "@/pages/purchase/bills";
import ReportsSalesPage from "@/pages/reports/sales";
import ReportsPurchasePage from "@/pages/reports/purchase";
import ReportsArAgingPage from "@/pages/reports/ar-aging";
import ReportsApAgingPage from "@/pages/reports/ap-aging";
import ReportsInventoryValuationPage from "@/pages/reports/inventory-valuation";
import ApprovalsPage from "@/pages/approvals/index";
import AccountingAccountsPage from "@/pages/accounting/accounts";
import AccountingJournalsPage from "@/pages/accounting/journals";
import AccountingTaxesPage from "@/pages/accounting/taxes";
import AccountingEntriesPage from "@/pages/accounting/entries";
import AccountingEntryDetailPage from "@/pages/accounting/entry-detail";
import AccountingJournalItemsPage from "@/pages/accounting/journal-items";
import AccountingPaymentsPage from "@/pages/accounting/payments";
import AccountingSettingsPage from "@/pages/accounting/settings";
import AccountingTrialBalancePage from "@/pages/accounting/reports/trial-balance";
import AccountingGeneralLedgerPage from "@/pages/accounting/reports/general-ledger";
import AccountingProfitLossPage from "@/pages/accounting/reports/profit-loss";
import AccountingBalanceSheetPage from "@/pages/accounting/reports/balance-sheet";
import AccountingReconciliationPage from "@/pages/accounting/reconciliation";
import CorrespondencesPage from "@/pages/correspondences";
import EmailInboxPage from "@/pages/email-inbox";
import ExpenseListPage from "@/pages/expense/index";
import ExpenseEditorPage from "@/pages/expense/editor";
import ExpenseCategoriesPage from "@/pages/expense/categories";
import ExpenseReportsPage from "@/pages/expense/reports";
import PortalProductOrdersPage from "@/pages/portal-product-orders";
import LogisticsQuotationReplyPage from "@/pages/logistics-quotation-reply";
import LogisticsVendorQuotePage from "@/pages/logistics-vendor-quote";
import SportCenterSchedulePage from "@/pages/sport-center-schedule";
import SportCenterReportPage from "@/pages/sport-center-report";
import { ProtectedRoute } from "@/components/ProtectedRoute";

const PR = (C: React.ComponentType) => () => <ProtectedRoute component={C} />;

export function AppRoutes({ rootGuard }: { rootGuard?: React.ComponentType }) {
  return (
    <Switch>
      {rootGuard && <Route path="/" component={rootGuard} />}
      <Route path="/welcome" component={WelcomePage} />
      <Route path="/dashboard" component={PR(DashboardPage)} />
      <Route path="/ecommerce" component={PR(EcommercePage)} />
      <Route path="/trading" component={PR(TradingPage)} />
      <Route path="/pos" component={PR(PosPage)} />
      <Route path="/pos-inventory/branches" component={PR(PosBranchesPage)} />
      <Route path="/pos-inventory/warehouses" component={PR(PosWarehousesPage)} />
      <Route path="/pos-inventory/racks" component={PR(PosRacksPage)} />
      <Route path="/pos-inventory/items" component={PR(PosInventoryItemsPage)} />
      <Route path="/pos-inventory/stocks" component={PR(PosInventoryStocksPage)} />
      <Route path="/pos-inventory/recipes" component={PR(PosRecipesPage)} />
      <Route path="/products/items" component={PR(ProductItemsPage)} />
      <Route path="/products/recipes" component={PR(ProductRecipesPage)} />
      <Route path="/pos-inventory/transfers" component={PR(PosStockTransfersPage)} />
      <Route path="/pos-inventory/returns" component={PR(PosStockReturnsPage)} />
      <Route path="/pos-inventory/losses" component={PR(PosStockLossesPage)} />
      <Route path="/pos-inventory/opname" component={PR(PosStockOpnamePage)} />
      <Route path="/pos-inventory/mutations" component={PR(PosStockMutationsPage)} />
      <Route path="/pos-inventory/dashboard" component={PR(PosInventoryDashboardPage)} />
      <Route path="/pos-inventory/qr-generator" component={PR(PosQrGeneratorPage)} />
      <Route path="/pos-inventory/qr-scanner" component={PR(PosQrScannerPage)} />
      <Route path="/logistics" component={PR(LogisticsPage)} />
      <Route path="/logistics/freight" component={PR(LogisticsFreightPage)} />
      <Route path="/logistics/freight/new" component={PR(LogisticsFreightEditorPage)} />
      <Route path="/logistics/freight/:id/bl" component={PR(LogisticsFreightBLPage)} />
      <Route path="/logistics/freight/:id/edit" component={PR(LogisticsFreightEditorPage)} />
      <Route path="/logistics/freight/:id" component={PR(LogisticsFreightDetailPage)} />
      <Route path="/logistics/portal-orders" component={PR(LogisticsPortalOrdersPage)} />
      <Route path="/logistics/portal-orders/:id" component={PR(LogisticsPortalOrderDetailPage)} />
      <Route path="/logistics/drivers" component={PR(LogisticsDriversPage)} />
      <Route path="/logistics/driver-performance" component={PR(LogisticsDriverPerformancePage)} />
      <Route path="/logistics/vendors" component={PR(LogisticsVendorsPage)} />
      <Route path="/logistics/vendor-quote" component={LogisticsVendorQuotePage} />
      <Route path="/logistics/quotation-reply/:token" component={LogisticsQuotationReplyPage} />
      <Route path="/sales" component={PR(SalesDashboardPage)} />
      <Route path="/sales/documents" component={PR(SalesDocumentsListPage)} />
      <Route path="/sales/documents/new" component={PR(SalesDocumentEditorPage)} />
      <Route path="/sales/documents/:id" component={PR(SalesDocumentEditorPage)} />
      <Route path="/sales/ai-drafts" component={PR(AiDraftsPage)} />
      <Route path="/sales/customers" component={PR(CustomersPage)} />
      <Route path="/sales/invoices" component={PR(SalesInvoicesPage)} />
      <Route path="/sales/items" component={PR(SalesItemsPage)} />
      <Route path="/purchase" component={PR(PurchaseDashboardPage)} />
      <Route path="/purchase/pr" component={PR(PurchaseRequestListPage)} />
      <Route path="/purchase/pr/new" component={PR(PurchaseRequestEditorPage)} />
      <Route path="/purchase/pr/:id" component={PR(PurchaseRequestEditorPage)} />
      <Route path="/purchase/documents" component={PR(PurchaseDocumentsListPage)} />
      <Route path="/purchase/documents/new" component={PR(PurchaseDocumentEditorPage)} />
      <Route path="/purchase/documents/:id" component={PR(PurchaseDocumentEditorPage)} />
      <Route path="/purchase/rfq" component={() => <ProtectedRoute component={() => <PurchaseDocumentsListPage kind="rfq" />} />} />
      <Route path="/purchase/rfq/new" component={PR(PurchaseDocumentEditorPage)} />
      <Route path="/purchase/rfq/:id" component={PR(PurchaseDocumentEditorPage)} />
      <Route path="/purchase/orders" component={() => <ProtectedRoute component={() => <PurchaseDocumentsListPage kind="order" />} />} />
      <Route path="/purchase/orders/:id" component={PR(PurchaseDocumentEditorPage)} />
      <Route path="/purchase/vendors" component={PR(VendorsPage)} />
      <Route path="/purchase/vendors/:id" component={PR(VendorDetailPage)} />
      <Route path="/purchase/bills" component={PR(PurchaseBillsPage)} />
      <Route path="/reports/sales" component={PR(ReportsSalesPage)} />
      <Route path="/reports/purchase" component={PR(ReportsPurchasePage)} />
      <Route path="/reports/ar-aging" component={PR(ReportsArAgingPage)} />
      <Route path="/reports/ap-aging" component={PR(ReportsApAgingPage)} />
      <Route path="/reports/inventory-valuation" component={PR(ReportsInventoryValuationPage)} />
      <Route path="/approvals" component={PR(ApprovalsPage)} />
      <Route path="/accounting/accounts" component={PR(AccountingAccountsPage)} />
      <Route path="/accounting/journals" component={PR(AccountingJournalsPage)} />
      <Route path="/accounting/taxes" component={PR(AccountingTaxesPage)} />
      <Route path="/accounting/entries" component={PR(AccountingEntriesPage)} />
      <Route path="/accounting/entries/:id" component={PR(AccountingEntryDetailPage)} />
      <Route path="/accounting/journal-items" component={PR(AccountingJournalItemsPage)} />
      <Route path="/accounting/payments" component={PR(AccountingPaymentsPage)} />
      <Route path="/accounting/settings" component={PR(AccountingSettingsPage)} />
      <Route path="/accounting/reconciliation" component={PR(AccountingReconciliationPage)} />
      <Route path="/accounting/reports/trial-balance" component={PR(AccountingTrialBalancePage)} />
      <Route path="/accounting/reports/general-ledger" component={PR(AccountingGeneralLedgerPage)} />
      <Route path="/accounting/reports/profit-loss" component={PR(AccountingProfitLossPage)} />
      <Route path="/accounting/reports/balance-sheet" component={PR(AccountingBalanceSheetPage)} />
      <Route path="/correspondences" component={PR(CorrespondencesPage)} />
      <Route path="/email-inbox" component={PR(EmailInboxPage)} />
      <Route path="/expense/new" component={PR(ExpenseEditorPage)} />
      <Route path="/expense/categories" component={PR(ExpenseCategoriesPage)} />
      <Route path="/expense/reports" component={PR(ExpenseReportsPage)} />
      <Route path="/expense/:id" component={PR(ExpenseEditorPage)} />
      <Route path="/expense" component={PR(ExpenseListPage)} />
      <Route path="/portal-product-orders" component={PR(PortalProductOrdersPage)} />
      <Route path="/settings/uom" component={PR(UomPage)} />
      <Route path="/settings/ai-chatbot" component={PR(AiChatbotSettingsPage)} />
      <Route path="/settings/ai-scan" component={PR(AiScanSettingsPage)} />
      <Route path="/settings" component={PR(SettingsPage)} />
      <Route path="/users" component={PR(UsersPage)} />
      <Route path="/sport-center/schedule" component={PR(SportCenterSchedulePage)} />
      <Route path="/sport-center/reports" component={PR(SportCenterReportPage)} />
      <Route component={NotFound} />
    </Switch>
  );
}
