import type { ServiceTemplate } from "./types.js";

export const serviceTemplates: Record<string, ServiceTemplate> = {

  // ── 1. product ───────────────────────────────────────────────────────────────
  product: {
    serviceType: "product",
    label: "Produk",
    emoji: "📦",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "product_name",       label: "Nama Produk",               type: "text",     required: true,  section: "both" },
      { key: "brand",              label: "Brand / Spesifikasi",       type: "text",                       section: "quotation" },
      { key: "unit_price",         label: "Harga per Satuan (Rp)",     type: "number",   required: true,  section: "quotation" },
      { key: "currency",           label: "Mata Uang",                 type: "select",   options: ["IDR","USD","SGD","EUR"], section: "quotation" },
      { key: "qty_available",      label: "Qty Tersedia",              type: "number",                     section: "quotation" },
      { key: "min_order",          label: "Minimum Order",             type: "number",                     section: "quotation" },
      { key: "unit",               label: "Satuan",                    type: "select",   required: true,  options: ["pcs","kg","ton","box","karton","lusin","unit"], section: "both" },
      { key: "lead_time",          label: "Lead Time (hari)",          type: "number",                     section: "quotation" },
      { key: "stock_status",       label: "Status Stok",               type: "select",   options: ["Ready Stock","Indent","Pre-order"], section: "quotation" },
      { key: "valid_until",        label: "Harga Berlaku Sampai",      type: "date",                       section: "quotation" },
      { key: "eta",                label: "Estimasi Pengiriman (hari)", type: "text",                      section: "quotation" },
      { key: "notes",              label: "Catatan",                   type: "textarea",                   section: "both" },
      { key: "stock_confirmation", label: "Konfirmasi Stok",           type: "select",   options: ["Ready","Partially Ready","Indent"], section: "operational" },
      { key: "packing_confirmation", label: "Status Packing",          type: "select",   options: ["Belum Packing","Sedang Packing","Sudah Packing"], section: "operational" },
      { key: "delivery_schedule",  label: "Jadwal Pengiriman",         type: "text",                       section: "operational" },
      { key: "invoice_vendor",     label: "No. Invoice Vendor",        type: "text",                       section: "operational" },
    ],
    requiredDocuments: [
      { key: "invoice_vendor_doc", label: "Invoice Vendor",   required: true  },
      { key: "packing_list",       label: "Packing List",     required: true  },
      { key: "delivery_receipt",   label: "Surat Jalan",      required: false },
    ],
    checklist: [
      { key: "stock_confirmed",    label: "Stok dikonfirmasi ke vendor"        },
      { key: "packing_complete",   label: "Packing selesai sesuai spesifikasi" },
      { key: "quality_checked",    label: "Quality check / inspeksi barang"    },
      { key: "invoice_received",   label: "Invoice vendor diterima"            },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "product_name", message: "Nama Produk wajib diisi" },
      { fieldKey: "unit_price",   message: "Harga per Satuan wajib diisi" },
      { fieldKey: "unit",         message: "Satuan wajib dipilih" },
    ],
  },

  // ── 2. trucking ──────────────────────────────────────────────────────────────
  trucking: {
    serviceType: "trucking",
    label: "Trucking",
    emoji: "🚛",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "truck_type",      label: "Jenis Armada",              type: "select",  required: true, options: ["CDD","CDE","Fuso","Tronton","Trailer 20ft","Trailer 40ft","Pick Up","Box Truck"], section: "quotation" },
      { key: "capacity",        label: "Kapasitas (ton)",           type: "number",                  section: "quotation" },
      { key: "area_pickup",     label: "Area Pickup",               type: "text",    required: true, placeholder: "Contoh: Cilincing, Jakarta Utara", section: "quotation" },
      { key: "area_delivery",   label: "Area Delivery",             type: "text",    required: true, placeholder: "Contoh: Cibitung, Bekasi", section: "quotation" },
      { key: "price",           label: "Harga Trucking (Rp)",       type: "number",  required: true, section: "quotation" },
      { key: "additional_charge", label: "Biaya Tambahan (Rp)",     type: "number",  placeholder: "Kosongkan jika tidak ada", section: "quotation" },
      { key: "eta_pickup",      label: "Estimasi Pickup",           type: "text",    placeholder: "Contoh: H+1 setelah konfirmasi", section: "quotation" },
      { key: "eta_delivery",    label: "Estimasi Delivery",         type: "text",    placeholder: "Contoh: 1–2 hari setelah pickup", section: "quotation" },
      { key: "valid_until",     label: "Rate Berlaku Sampai",       type: "date",                    section: "quotation" },
      { key: "notes",           label: "Catatan Penawaran",         type: "textarea",                section: "quotation" },
      { key: "driver_name",     label: "Nama Driver",               type: "text",    required: true, section: "operational" },
      { key: "driver_phone",    label: "No HP Driver",              type: "text",    required: true, section: "operational" },
      { key: "plate_number",    label: "Plat Nomor Kendaraan",      type: "text",    required: true, section: "operational" },
      { key: "vehicle_type",    label: "Jenis Kendaraan",           type: "text",                    section: "operational" },
      { key: "pickup_time",     label: "Waktu Pickup",              type: "text",                    section: "operational" },
      { key: "delivery_time",   label: "Waktu Delivery",            type: "text",                    section: "operational" },
      { key: "op_notes",        label: "Catatan Operasional",       type: "textarea",                section: "operational" },
    ],
    requiredDocuments: [
      { key: "surat_jalan",     label: "Surat Jalan",               required: true  },
      { key: "stnk_kir",        label: "STNK / KIR Kendaraan",      required: true  },
      { key: "sim_driver",      label: "SIM B2/BU Driver",          required: true  },
      { key: "surat_tugas",     label: "Surat Tugas Driver",        required: false },
    ],
    checklist: [
      { key: "driver_confirmed",  label: "Driver dikonfirmasi dan siap"          },
      { key: "plate_verified",    label: "Plat nomor kendaraan terverifikasi"     },
      { key: "vehicle_checked",   label: "Kondisi kendaraan layak jalan"          },
      { key: "gps_active",        label: "GPS/Tracking aktif"                    },
      { key: "cargo_secured",     label: "Muatan diamankan dengan baik"           },
      { key: "sj_issued",         label: "Surat Jalan sudah diterbitkan"          },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "truck_type",   message: "Jenis Armada wajib dipilih"           },
      { fieldKey: "area_pickup",  message: "Area Pickup wajib diisi"              },
      { fieldKey: "area_delivery", message: "Area Delivery wajib diisi"           },
      { fieldKey: "price",        message: "Harga Trucking wajib diisi"           },
    ],
  },

  // ── 3. sea_freight ───────────────────────────────────────────────────────────
  sea_freight: {
    serviceType: "sea_freight",
    label: "Sea Freight",
    emoji: "🚢",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "shipping_line",     label: "Shipping Line / Forwarder", type: "text",    required: true, placeholder: "Contoh: Maersk, MSC", section: "quotation" },
      { key: "pol",               label: "Port of Loading (POL)",     type: "text",    required: true, placeholder: "Contoh: IDJKT", section: "quotation" },
      { key: "pod",               label: "Port of Discharge (POD)",   type: "text",    required: true, placeholder: "Contoh: SGSIN", section: "quotation" },
      { key: "container_type",    label: "Tipe Kontainer",            type: "select",  required: true, options: ["20' GP","40' GP","40' HC","45' HC","20' RF","40' RF"], section: "quotation" },
      { key: "freight_rate",      label: "Freight Rate",              type: "number",  required: true, section: "quotation" },
      { key: "currency",          label: "Mata Uang",                 type: "select",  required: true, options: ["USD","IDR","SGD","EUR","CNY"], section: "quotation" },
      { key: "etd",               label: "ETD",                       type: "date",                    section: "quotation" },
      { key: "eta",               label: "ETA",                       type: "date",                    section: "quotation" },
      { key: "transit_time",      label: "Transit Time (hari)",       type: "number",  required: true, section: "quotation" },
      { key: "free_time",         label: "Free Time Demurrage (hari)", type: "number",                 section: "quotation" },
      { key: "charges_include",   label: "Include Charges",           type: "textarea", placeholder: "Contoh: BL Fee, THC Origin", section: "quotation" },
      { key: "surcharge_note",    label: "Surcharge / Additional",    type: "textarea",                section: "quotation" },
      { key: "validity",          label: "Rate Berlaku Sampai",       type: "date",                    section: "quotation" },
      { key: "notes",             label: "Catatan",                   type: "textarea",                section: "quotation" },
      { key: "booking_number",    label: "Booking Number",            type: "text",    required: true, section: "operational" },
      { key: "vessel_name",       label: "Vessel / Kapal",            type: "text",                    section: "operational" },
      { key: "op_etd",            label: "ETD Aktual",                type: "text",                    section: "operational" },
      { key: "op_eta",            label: "ETA Aktual",                type: "text",                    section: "operational" },
      { key: "bl_number",         label: "BL Number",                 type: "text",                    section: "operational" },
    ],
    requiredDocuments: [
      { key: "bill_of_lading",    label: "Bill of Lading (BL)",       required: true  },
      { key: "packing_list",      label: "Packing List",              required: true  },
      { key: "commercial_invoice", label: "Commercial Invoice",       required: true  },
      { key: "shipping_instruction", label: "Shipping Instruction (SI)", required: true },
      { key: "coo",               label: "Certificate of Origin (COO)", required: false },
      { key: "msds",              label: "MSDS (jika DG/Hazmat)",     required: false },
    ],
    checklist: [
      { key: "booking_confirmed", label: "Booking dikonfirmasi ke shipping line" },
      { key: "si_submitted",      label: "SI (Shipping Instruction) disubmit"    },
      { key: "container_stuffed", label: "Kontainer sudah di-stuff"               },
      { key: "bl_released",       label: "BL diterbitkan"                         },
      { key: "docs_to_customer",  label: "Dokumen dikirim ke customer"            },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "shipping_line",  message: "Shipping Line / Forwarder wajib diisi" },
      { fieldKey: "pol",            message: "Port of Loading wajib diisi"            },
      { fieldKey: "pod",            message: "Port of Discharge wajib diisi"          },
      { fieldKey: "container_type", message: "Tipe Kontainer wajib dipilih"           },
      { fieldKey: "freight_rate",   message: "Freight Rate wajib diisi"               },
      { fieldKey: "transit_time",   message: "Transit Time wajib diisi"               },
    ],
  },

  // ── 4. air_freight ───────────────────────────────────────────────────────────
  air_freight: {
    serviceType: "air_freight",
    label: "Air Freight",
    emoji: "✈️",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "airline",          label: "Maskapai / Agent",            type: "text",    required: true, placeholder: "Contoh: Garuda Cargo, DHL", section: "quotation" },
      { key: "origin_airport",   label: "Bandara Asal (IATA)",         type: "text",    required: true, placeholder: "Contoh: CGK", section: "quotation" },
      { key: "dest_airport",     label: "Bandara Tujuan (IATA)",       type: "text",    required: true, placeholder: "Contoh: SIN", section: "quotation" },
      { key: "rate_per_kg",      label: "Rate per kg",                 type: "number",  required: true, section: "quotation" },
      { key: "currency",         label: "Mata Uang",                   type: "select",  required: true, options: ["IDR","USD","SGD","EUR","CNY"], section: "quotation" },
      { key: "min_charge",       label: "Minimum Charge",              type: "number",                  section: "quotation" },
      { key: "fsc",              label: "FSC / SSC / MYC",             type: "text",    placeholder: "Kosongkan jika tidak ada", section: "quotation" },
      { key: "etd",              label: "ETD / Jadwal Penerbangan",    type: "date",                    section: "quotation" },
      { key: "transit_time",     label: "Transit Time (hari)",         type: "number",  required: true, section: "quotation" },
      { key: "chargeable_weight_rule", label: "Chargeable Weight Rule", type: "select", options: ["Actual Weight","Volume Weight","Higher of Both"], section: "quotation" },
      { key: "charges_include",  label: "Include Charges",             type: "textarea",                section: "quotation" },
      { key: "validity",         label: "Rate Berlaku Sampai",         type: "date",                    section: "quotation" },
      { key: "notes",            label: "Catatan",                     type: "textarea",                section: "quotation" },
      { key: "booking_number",   label: "Booking Number",              type: "text",    required: true, section: "operational" },
      { key: "flight_number",    label: "Nomor Penerbangan",           type: "text",                    section: "operational" },
      { key: "op_etd",           label: "ETD Aktual",                  type: "text",                    section: "operational" },
      { key: "op_eta",           label: "ETA Aktual",                  type: "text",                    section: "operational" },
      { key: "awb_number",       label: "AWB Number",                  type: "text",                    section: "operational" },
    ],
    requiredDocuments: [
      { key: "air_waybill",      label: "Air Waybill (AWB)",           required: true  },
      { key: "packing_list",     label: "Packing List",                required: true  },
      { key: "commercial_invoice", label: "Commercial Invoice",        required: true  },
      { key: "msds",             label: "MSDS (jika DG/Hazmat)",       required: false },
      { key: "coo",              label: "Certificate of Origin (COO)", required: false },
    ],
    checklist: [
      { key: "booking_confirmed", label: "Booking dikonfirmasi ke maskapai/agent" },
      { key: "cargo_accepted",    label: "Cargo diterima di bandara asal"          },
      { key: "awb_issued",        label: "AWB sudah diterbitkan"                   },
      { key: "flight_departed",   label: "Penerbangan sudah berangkat"             },
      { key: "docs_to_customer",  label: "Dokumen (AWB, Invoice) dikirim ke customer" },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "airline",       message: "Maskapai / Agent wajib diisi"     },
      { fieldKey: "origin_airport", message: "Bandara Asal wajib diisi"        },
      { fieldKey: "dest_airport",  message: "Bandara Tujuan wajib diisi"       },
      { fieldKey: "rate_per_kg",   message: "Rate per kg wajib diisi"          },
      { fieldKey: "transit_time",  message: "Transit Time wajib diisi"         },
    ],
  },

  // ── 5. ppjk ──────────────────────────────────────────────────────────────────
  ppjk: {
    serviceType: "ppjk",
    label: "PPJK / Customs Clearance",
    emoji: "📋",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "doc_type",       label: "Jenis Dokumen BC",         type: "select",  required: true, options: ["PIB Jalur Hijau","PIB Jalur Kuning","PIB Jalur Merah","PIB Jalur Prioritas","PIBK","PEB","BCF"], section: "quotation" },
      { key: "hs_code",        label: "HS Code (opsional)",       type: "text",                    section: "quotation" },
      { key: "customs_service", label: "Estimasi Biaya Jasa",     type: "number",  required: true, section: "quotation" },
      { key: "currency",       label: "Mata Uang",                type: "select",  required: true, options: ["IDR","USD"], section: "quotation" },
      { key: "duty_tax_estimate", label: "Estimasi Duty/Tax",     type: "number",                  section: "quotation" },
      { key: "docs_required",  label: "Dokumen yang Dibutuhkan",  type: "textarea",                section: "quotation" },
      { key: "sla",            label: "SLA Proses (hari kerja)",  type: "number",                  section: "quotation" },
      { key: "undername",      label: "Biaya Undername (Rp)",     type: "number",  placeholder: "Kosongkan jika tidak ada", section: "quotation" },
      { key: "notes",          label: "Catatan / Compliance",     type: "textarea",                section: "quotation" },
      { key: "nomor_aju",      label: "Nomor Aju",                type: "text",    required: true, section: "operational" },
      { key: "jenis_dokumen",  label: "Jenis Dokumen Aktual",     type: "text",                    section: "operational" },
      { key: "status_customs", label: "Status Customs",           type: "select",  options: ["Dalam Proses","Jalur Hijau","Jalur Kuning","Jalur Merah","SPPB Terbit"], section: "operational" },
      { key: "billing_info",   label: "Info Billing / Pajak",     type: "textarea",                section: "operational" },
    ],
    requiredDocuments: [
      { key: "pib_peb",          label: "PIB / PEB",                required: true  },
      { key: "packing_list",     label: "Packing List",             required: true  },
      { key: "commercial_invoice", label: "Commercial Invoice",     required: true  },
      { key: "coo",              label: "COO (jika diperlukan)",    required: false },
      { key: "msds",             label: "MSDS / Analisa (jika DG)", required: false },
    ],
    checklist: [
      { key: "docs_complete",    label: "Dokumen pabean lengkap dan sesuai"   },
      { key: "aju_submitted",    label: "Pengajuan (nomor aju) dikirim"       },
      { key: "jalur_determined", label: "Jalur pemeriksaan ditentukan"        },
      { key: "sppb_issued",      label: "SPPB terbit"                         },
      { key: "goods_released",   label: "Barang keluar dari kawasan pabean"   },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "doc_type",        message: "Jenis Dokumen BC wajib dipilih"      },
      { fieldKey: "customs_service", message: "Estimasi Biaya Jasa wajib diisi"     },
      { fieldKey: "currency",        message: "Mata Uang wajib dipilih"             },
    ],
  },

  // ── 6. handling ──────────────────────────────────────────────────────────────
  handling: {
    serviceType: "handling",
    label: "Handling / Warehouse",
    emoji: "🏭",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "location",         label: "Lokasi Warehouse",         type: "text",    required: true, placeholder: "Contoh: Cikarang Barat", section: "quotation" },
      { key: "area_sqm",         label: "Luas Tersedia (m²)",       type: "number",                  section: "quotation" },
      { key: "handling_fee",     label: "Handling Fee (Rp)",        type: "number",  required: true, section: "quotation" },
      { key: "storage_fee",      label: "Storage Fee (Rp/m²/bulan)", type: "number",                 section: "quotation" },
      { key: "free_storage",     label: "Free Storage (hari)",      type: "number",                  section: "quotation" },
      { key: "loading_unloading_fee", label: "Loading/Unloading Fee (Rp/ton)", type: "number",       section: "quotation" },
      { key: "temperature",      label: "Suhu / Tipe",              type: "select",  options: ["Ambient","Chilled (2–8°C)","Frozen (-18°C)","AC Room"], section: "quotation" },
      { key: "rack_system",      label: "Sistem Racking",           type: "select",  options: ["Selective","Drive-in","Push Back","Floor Storage","Mezzanine"], section: "quotation" },
      { key: "sla",              label: "SLA Proses (hari)",        type: "number",                  section: "quotation" },
      { key: "equipment",        label: "Equipment Support",        type: "text",    placeholder: "Contoh: Forklift 3 ton, CCTV 24 jam", section: "quotation" },
      { key: "security",         label: "Keamanan",                 type: "text",    placeholder: "Contoh: CCTV 24 jam, Satpam", section: "quotation" },
      { key: "notes",            label: "Catatan",                  type: "textarea",                section: "quotation" },
      { key: "wh_receipt_number", label: "No. Warehouse Receipt",   type: "text",    required: true, section: "operational" },
      { key: "inbound_date",     label: "Tanggal Inbound",          type: "date",                    section: "operational" },
      { key: "qty_received",     label: "Qty Diterima",             type: "number",                  section: "operational" },
      { key: "condition_note",   label: "Kondisi Barang",           type: "textarea",                section: "operational" },
      { key: "outbound_date",    label: "Tanggal Outbound",         type: "date",                    section: "operational" },
      { key: "op_notes",         label: "Catatan Operasional",      type: "textarea",                section: "operational" },
    ],
    requiredDocuments: [
      { key: "warehouse_receipt", label: "Warehouse Receipt (WR)", required: true  },
      { key: "packing_list",      label: "Packing List",           required: true  },
      { key: "surat_pengantar",   label: "Surat Pengantar Barang", required: false },
    ],
    checklist: [
      { key: "inbound_verified",  label: "Barang inbound diverifikasi qty & kondisi" },
      { key: "storage_allocated", label: "Lokasi penyimpanan dialokasikan"           },
      { key: "condition_noted",   label: "Kondisi barang dicatat dan difoto"         },
      { key: "wr_issued",         label: "Warehouse Receipt diterbitkan"             },
      { key: "wms_updated",       label: "WMS / catatan stok diupdate"               },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "location",     message: "Lokasi Warehouse wajib diisi"     },
      { fieldKey: "handling_fee", message: "Handling Fee wajib diisi"         },
    ],
  },

  // ── 7. document ──────────────────────────────────────────────────────────────
  document: {
    serviceType: "document",
    label: "Document / Additional Service",
    emoji: "📄",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "service_name",  label: "Nama Layanan",               type: "text",    required: true, section: "quotation" },
      { key: "description",   label: "Deskripsi Layanan",          type: "textarea",                section: "quotation" },
      { key: "price",         label: "Harga",                      type: "number",  required: true, section: "quotation" },
      { key: "currency",      label: "Mata Uang",                  type: "select",  required: true, options: ["IDR","USD"], section: "quotation" },
      { key: "sla",           label: "SLA / Lead Time (hari)",     type: "number",                  section: "quotation" },
      { key: "docs_required", label: "Dokumen yang Dibutuhkan",    type: "textarea",                section: "quotation" },
      { key: "validity",      label: "Berlaku Sampai",             type: "date",                    section: "quotation" },
      { key: "notes",         label: "Catatan",                    type: "textarea",                section: "quotation" },
      { key: "doc_reference", label: "No. Referensi Dokumen",      type: "text",    required: true, section: "operational" },
      { key: "issue_date",    label: "Tanggal Terbit",             type: "date",                    section: "operational" },
      { key: "status_doc",    label: "Status Dokumen",             type: "select",  options: ["Dalam Proses","Selesai","Ditolak","Revisi"], section: "operational" },
      { key: "op_notes",      label: "Catatan Operasional",        type: "textarea",                section: "operational" },
    ],
    requiredDocuments: [
      { key: "supporting_doc", label: "Dokumen Pendukung", required: false },
    ],
    checklist: [
      { key: "doc_received",  label: "Dokumen dari klien diterima"   },
      { key: "doc_processed", label: "Dokumen diproses"               },
      { key: "doc_completed", label: "Dokumen selesai / diterbitkan"  },
      { key: "doc_delivered", label: "Dokumen diserahkan ke klien"    },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "service_name", message: "Nama Layanan wajib diisi" },
      { fieldKey: "price",        message: "Harga wajib diisi"        },
      { fieldKey: "currency",     message: "Mata Uang wajib dipilih"  },
    ],
  },

  // ── 8. exim_service ──────────────────────────────────────────────────────────
  exim_service: {
    serviceType: "exim_service",
    label: "Exim Service",
    emoji: "🌐",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "service_type",   label: "Layanan",                   type: "select",  required: true, options: ["Import Door to Door","Export Door to Door","Import Port to Port","Export Port to Port","Full Service"], section: "quotation" },
      { key: "origin_country", label: "Negara Asal",               type: "text",    required: true, section: "quotation" },
      { key: "dest_country",   label: "Negara Tujuan",             type: "text",    required: true, section: "quotation" },
      { key: "price",          label: "Harga",                     type: "number",  required: true, section: "quotation" },
      { key: "currency",       label: "Mata Uang",                 type: "select",  required: true, options: ["IDR","USD","SGD","EUR","CNY"], section: "quotation" },
      { key: "transit_time",   label: "Transit Time (hari)",       type: "number",                  section: "quotation" },
      { key: "incoterms",      label: "Incoterms",                 type: "select",  options: ["EXW","FOB","CIF","DAP","DDP","FCA","CPT","CIP"], section: "quotation" },
      { key: "validity",       label: "Masa Berlaku (hari)",       type: "number",                  section: "quotation" },
      { key: "notes",          label: "Catatan",                   type: "textarea",                section: "quotation" },
      { key: "job_reference",  label: "No. Job Reference",         type: "text",    required: true, section: "operational" },
      { key: "shipment_status", label: "Status Shipment",          type: "select",  options: ["Booking","In Transit Origin","On Vessel/Flight","Arrived Destination","Customs Clearance","Out for Delivery","Delivered"], section: "operational" },
      { key: "actual_etd",     label: "ETD Aktual",                type: "date",                    section: "operational" },
      { key: "actual_eta",     label: "ETA Aktual",                type: "date",                    section: "operational" },
      { key: "tracking_info",  label: "Info Tracking",             type: "textarea",                section: "operational" },
      { key: "op_notes",       label: "Catatan Operasional",       type: "textarea",                section: "operational" },
    ],
    requiredDocuments: [
      { key: "commercial_invoice", label: "Commercial Invoice",    required: true  },
      { key: "packing_list",       label: "Packing List",          required: true  },
      { key: "bl_awb",             label: "BL / AWB",              required: true  },
      { key: "coo",                label: "Certificate of Origin", required: false },
      { key: "msds",               label: "MSDS (jika DG)",        required: false },
    ],
    checklist: [
      { key: "booking_confirmed",  label: "Booking dikonfirmasi"                     },
      { key: "cargo_ready",        label: "Cargo siap di origin"                     },
      { key: "docs_complete",      label: "Dokumen ekspor/impor lengkap"             },
      { key: "customs_cleared",    label: "Bea cukai cleared di origin & destination" },
      { key: "delivered",          label: "Barang delivered ke consignee"            },
    ],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "service_type",   message: "Layanan wajib dipilih"          },
      { fieldKey: "origin_country", message: "Negara Asal wajib diisi"        },
      { fieldKey: "dest_country",   message: "Negara Tujuan wajib diisi"      },
      { fieldKey: "price",          message: "Harga wajib diisi"              },
    ],
  },

  // ── 9. customer_shipment ─────────────────────────────────────────────────────
  customer_shipment: {
    serviceType: "customer_shipment",
    label: "Permintaan Pengiriman",
    emoji: "📦",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "cargo_name",     label: "Nama / Jenis Barang",              type: "text",    required: true, section: "quotation" },
      { key: "origin",         label: "Kota / Negara Asal",               type: "text",    required: true, section: "quotation" },
      { key: "destination",    label: "Kota / Negara Tujuan",             type: "text",    required: true, section: "quotation" },
      { key: "weight",         label: "Berat Perkiraan (kg)",             type: "number",                  section: "quotation" },
      { key: "volume",         label: "Volume / Dimensi (m³ atau cm)",    type: "text",                    section: "quotation" },
      { key: "qty",            label: "Jumlah",                           type: "number",                  section: "quotation" },
      { key: "unit",           label: "Satuan",                           type: "select",  options: ["pcs","kg","ton","box","palet","kontainer"], section: "quotation" },
      { key: "service_pref",   label: "Layanan yang Diinginkan",          type: "select",  options: ["Sea Freight","Air Freight","Trucking","Customs Clearance","Door to Door","Lainnya"], section: "quotation" },
      { key: "preferred_date", label: "Tanggal Pengiriman yang Diinginkan", type: "date",                   section: "quotation" },
      { key: "incoterms",      label: "Incoterms (jika ada)",             type: "select",  options: ["EXW","FOB","CIF","DAP","DDP","Tidak tahu"], section: "quotation" },
      { key: "special_req",    label: "Persyaratan Khusus",               type: "textarea",                section: "quotation" },
      { key: "notes",          label: "Catatan Tambahan",                 type: "textarea",                section: "quotation" },
    ],
    requiredDocuments: [],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "cargo_name",  message: "Nama / Jenis Barang wajib diisi"  },
      { fieldKey: "origin",      message: "Kota / Negara Asal wajib diisi"   },
      { fieldKey: "destination", message: "Kota / Negara Tujuan wajib diisi" },
    ],
  },

  // ── 10. customer_quote ───────────────────────────────────────────────────────
  customer_quote: {
    serviceType: "customer_quote",
    label: "Permintaan Penawaran Harga",
    emoji: "💼",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "service_type",  label: "Layanan yang Dibutuhkan",        type: "select",  required: true, options: ["Freight Forwarding","Custom Clearance","Trucking","Warehousing","Exim Consulting","Full Logistics","Lainnya"], section: "quotation" },
      { key: "cargo_desc",    label: "Deskripsi Barang / Komoditi",    type: "textarea", required: true, section: "quotation" },
      { key: "origin_country", label: "Negara / Kota Asal",           type: "text",    required: true, section: "quotation" },
      { key: "dest_country",   label: "Negara / Kota Tujuan",         type: "text",    required: true, section: "quotation" },
      { key: "weight_volume", label: "Berat / Volume Perkiraan",       type: "text",                    section: "quotation" },
      { key: "frequency",     label: "Frekuensi Pengiriman",           type: "select",  options: ["Sekali","Mingguan","2x/bulan","Bulanan","Berkala (proyek)"], section: "quotation" },
      { key: "budget",        label: "Budget Perkiraan",               type: "text",                    section: "quotation" },
      { key: "timeline",      label: "Target Tanggal Pengiriman Pertama", type: "date",                 section: "quotation" },
      { key: "notes",         label: "Informasi Tambahan",             type: "textarea",                section: "quotation" },
    ],
    requiredDocuments: [],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "service_type",   message: "Layanan yang Dibutuhkan wajib dipilih" },
      { fieldKey: "cargo_desc",     message: "Deskripsi Barang wajib diisi"          },
      { fieldKey: "origin_country", message: "Negara / Kota Asal wajib diisi"        },
      { fieldKey: "dest_country",   message: "Negara / Kota Tujuan wajib diisi"      },
    ],
  },

  // ── 11. customer_document ────────────────────────────────────────────────────
  customer_document: {
    serviceType: "customer_document",
    label: "Pengiriman Dokumen",
    emoji: "📋",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "doc_type",         label: "Jenis Dokumen",            type: "select",  required: true, options: ["Invoice","Packing List","Bill of Lading","AWB","COO","MSDS","Phytosanitary","Fumigation","Lainnya"], section: "quotation" },
      { key: "doc_reference",    label: "Nomor Referensi / PO",     type: "text",                    section: "quotation" },
      { key: "issued_by",        label: "Diterbitkan Oleh",         type: "text",                    section: "quotation" },
      { key: "issued_date",      label: "Tanggal Terbit",           type: "date",                    section: "quotation" },
      { key: "related_shipment", label: "Terkait Shipment / Order", type: "text",                    section: "quotation" },
      { key: "notes",            label: "Keterangan",               type: "textarea",                section: "quotation" },
    ],
    requiredDocuments: [],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "doc_type", message: "Jenis Dokumen wajib dipilih" },
    ],
  },

  // ── 12. customer_complaint ───────────────────────────────────────────────────
  customer_complaint: {
    serviceType: "customer_complaint",
    label: "Keluhan / Klaim",
    emoji: "⚠️",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "order_ref",           label: "Nomor Order / Shipment",        type: "text",    required: true, section: "quotation" },
      { key: "complaint_type",      label: "Jenis Keluhan",                 type: "select",  required: true, options: ["Keterlambatan","Kerusakan Barang","Kehilangan Barang","Dokumen Salah","Overcharge","Pelayanan","Lainnya"], section: "quotation" },
      { key: "incident_date",       label: "Tanggal Kejadian",              type: "date",                    section: "quotation" },
      { key: "description",         label: "Deskripsi Masalah",             type: "textarea", required: true, section: "quotation" },
      { key: "claimed_amount",      label: "Nilai Klaim (Rp)",              type: "number",                  section: "quotation" },
      { key: "expected_resolution", label: "Penyelesaian yang Diharapkan",  type: "textarea",                section: "quotation" },
    ],
    requiredDocuments: [
      { key: "complaint_photo", label: "Foto Kerusakan (jika ada)",    required: false },
      { key: "claim_support",   label: "Dokumen Pendukung Klaim",      required: false },
    ],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "order_ref",       message: "Nomor Order / Shipment wajib diisi" },
      { fieldKey: "complaint_type",  message: "Jenis Keluhan wajib dipilih"        },
      { fieldKey: "description",     message: "Deskripsi Masalah wajib diisi"      },
    ],
  },

  // ── 13. customer_product ─────────────────────────────────────────────────────
  customer_product: {
    serviceType: "customer_product",
    label: "Pemesanan Produk",
    emoji: "🛒",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "product_name",          label: "Nama / Jenis Produk",              type: "text",    required: true, placeholder: "Contoh: Green Bean Arabica Grade 1", section: "quotation" },
      { key: "brand_spec",            label: "Brand / Spesifikasi",              type: "text",    placeholder: "Contoh: Grade A, moisture max 12%", section: "quotation" },
      { key: "qty",                   label: "Jumlah yang Dipesan",              type: "number",  required: true, section: "quotation" },
      { key: "unit",                  label: "Satuan",                           type: "select",  required: true, options: ["pcs","kg","ton","box","karton","sak","lusin","unit","lainnya"], section: "quotation" },
      { key: "target_price",          label: "Target Harga (Rp)",                type: "number",  placeholder: "Kosongkan jika tidak ada target", section: "quotation" },
      { key: "currency",              label: "Mata Uang",                        type: "select",  options: ["IDR","USD","SGD","EUR"], section: "quotation" },
      { key: "delivery_address",      label: "Alamat Pengiriman",                type: "textarea", required: true, section: "quotation" },
      { key: "preferred_delivery_date", label: "Tanggal Pengiriman yang Diinginkan", type: "date",                section: "quotation" },
      { key: "payment_terms",         label: "Cara Pembayaran",                  type: "select",  options: ["Cash","Transfer 50% DP","Transfer Lunas","Credit 30 hari","Credit 45 hari","Lainnya"], section: "quotation" },
      { key: "notes",                 label: "Catatan Tambahan",                 type: "textarea", placeholder: "Persyaratan khusus, kemasan, dokumen, dll.", section: "quotation" },
    ],
    requiredDocuments: [],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "product_name",    message: "Nama / Jenis Produk wajib diisi"   },
      { fieldKey: "qty",             message: "Jumlah yang Dipesan wajib diisi"   },
      { fieldKey: "unit",            message: "Satuan wajib dipilih"              },
      { fieldKey: "delivery_address", message: "Alamat Pengiriman wajib diisi"    },
    ],
  },

  // ── 14. admin_checklist ──────────────────────────────────────────────────────
  admin_checklist: {
    serviceType: "admin_checklist",
    label: "Checklist Proses",
    emoji: "✅",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "process_name",  label: "Nama Proses / Pekerjaan",  type: "text",    required: true, section: "quotation" },
      { key: "order_ref",     label: "Nomor Order / Referensi",  type: "text",                    section: "quotation" },
      { key: "responsible",   label: "Penanggung Jawab",         type: "text",    required: true, section: "quotation" },
      { key: "check_date",    label: "Tanggal Pengecekan",       type: "date",                    section: "quotation" },
      { key: "item_1",        label: "Checklist Item 1",         type: "select",  options: ["✅ Selesai","⏳ Proses","❌ Belum"], section: "quotation" },
      { key: "item_2",        label: "Checklist Item 2",         type: "select",  options: ["✅ Selesai","⏳ Proses","❌ Belum"], section: "quotation" },
      { key: "item_3",        label: "Checklist Item 3",         type: "select",  options: ["✅ Selesai","⏳ Proses","❌ Belum"], section: "quotation" },
      { key: "overall_status", label: "Status Keseluruhan",      type: "select",  required: true, options: ["Completed","In Progress","Blocked","Cancelled"], section: "quotation" },
      { key: "issues",        label: "Kendala / Issues",         type: "textarea",                section: "quotation" },
      { key: "next_action",   label: "Tindakan Selanjutnya",     type: "textarea",                section: "quotation" },
      { key: "notes",         label: "Catatan",                  type: "textarea",                section: "quotation" },
    ],
    requiredDocuments: [],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "process_name",   message: "Nama Proses / Pekerjaan wajib diisi" },
      { fieldKey: "responsible",    message: "Penanggung Jawab wajib diisi"        },
      { fieldKey: "overall_status", message: "Status Keseluruhan wajib dipilih"    },
    ],
  },

  // ── 15. admin_handover ───────────────────────────────────────────────────────
  admin_handover: {
    serviceType: "admin_handover",
    label: "Serah Terima Pekerjaan",
    emoji: "🤝",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "job_ref",           label: "Nomor Job / Order",      type: "text",    required: true, section: "quotation" },
      { key: "from_staff",        label: "Diserahkan Oleh",        type: "text",    required: true, section: "quotation" },
      { key: "to_staff",          label: "Diterima Oleh",          type: "text",    required: true, section: "quotation" },
      { key: "handover_date",     label: "Tanggal Serah Terima",   type: "date",    required: true, section: "quotation" },
      { key: "job_description",   label: "Deskripsi Pekerjaan",    type: "textarea", required: true, section: "quotation" },
      { key: "current_status",    label: "Status Saat Ini",        type: "select",  required: true, options: ["Baru Mulai","Sedang Berjalan","Menunggu Dokumen","Menunggu Vendor","Menunggu Customer","Hampir Selesai"], section: "quotation" },
      { key: "pending_items",     label: "Item yang Belum Selesai", type: "textarea",                section: "quotation" },
      { key: "important_contacts", label: "Kontak Penting",        type: "textarea",                section: "quotation" },
      { key: "notes",             label: "Catatan Tambahan",       type: "textarea",                section: "quotation" },
    ],
    requiredDocuments: [],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "job_ref",         message: "Nomor Job / Order wajib diisi"   },
      { fieldKey: "from_staff",      message: "Diserahkan Oleh wajib diisi"     },
      { fieldKey: "to_staff",        message: "Diterima Oleh wajib diisi"       },
      { fieldKey: "handover_date",   message: "Tanggal Serah Terima wajib diisi" },
      { fieldKey: "job_description", message: "Deskripsi Pekerjaan wajib diisi"  },
      { fieldKey: "current_status",  message: "Status Saat Ini wajib dipilih"    },
    ],
  },

  // ── 16. admin_inspection ─────────────────────────────────────────────────────
  admin_inspection: {
    serviceType: "admin_inspection",
    label: "Laporan Inspeksi",
    emoji: "🔍",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "inspection_ref",  label: "Nomor Inspeksi / Referensi", type: "text",    required: true, section: "quotation" },
      { key: "location",        label: "Lokasi Inspeksi",            type: "text",    required: true, section: "quotation" },
      { key: "inspection_date", label: "Tanggal Inspeksi",           type: "date",    required: true, section: "quotation" },
      { key: "inspector",       label: "Nama Inspektor",             type: "text",    required: true, section: "quotation" },
      { key: "goods_desc",      label: "Deskripsi Barang / Aset",    type: "textarea", required: true, section: "quotation" },
      { key: "qty_checked",     label: "Jumlah Diperiksa",           type: "number",                  section: "quotation" },
      { key: "qty_ok",          label: "Jumlah OK",                  type: "number",                  section: "quotation" },
      { key: "qty_rejected",    label: "Jumlah Ditolak / Rusak",     type: "number",                  section: "quotation" },
      { key: "condition",       label: "Kondisi Umum",               type: "select",  required: true, options: ["Baik","Cukup Baik","Ada Kerusakan Minor","Kerusakan Signifikan","Ditolak"], section: "quotation" },
      { key: "findings",        label: "Temuan / Catatan",           type: "textarea",                section: "quotation" },
      { key: "recommendation",  label: "Rekomendasi",                type: "textarea",                section: "quotation" },
    ],
    requiredDocuments: [
      { key: "inspection_report", label: "Laporan Inspeksi",    required: true  },
      { key: "inspection_photo",  label: "Foto Dokumentasi",    required: false },
    ],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "inspection_ref",  message: "Nomor Inspeksi / Referensi wajib diisi" },
      { fieldKey: "location",        message: "Lokasi Inspeksi wajib diisi"            },
      { fieldKey: "inspection_date", message: "Tanggal Inspeksi wajib diisi"           },
      { fieldKey: "inspector",       message: "Nama Inspektor wajib diisi"             },
      { fieldKey: "goods_desc",      message: "Deskripsi Barang wajib diisi"           },
      { fieldKey: "condition",       message: "Kondisi Umum wajib dipilih"             },
    ],
  },

  // ── 17. admin_rfq_forward ────────────────────────────────────────────────────
  admin_rfq_forward: {
    serviceType: "admin_rfq_forward",
    label: "Forward RFQ Customer ke Vendor",
    emoji: "📨",
    version: "1.0.0",
    isActive: true,
    fields: [
      { key: "customer_name",     label: "Nama Customer / Perusahaan",               type: "text",    required: true, placeholder: "Contoh: PT Maju Bersama", section: "quotation" },
      { key: "rfq_ref",           label: "Nomor RFQ / Referensi Internal",           type: "text",    placeholder: "Contoh: RFQ/2025/001", section: "quotation" },
      { key: "service_needed",    label: "Layanan yang Dibutuhkan",                  type: "select",  required: true, options: ["Sea Freight","Air Freight","Trucking","Customs Clearance","Warehousing","Exim Full Service","Door to Door","Lainnya"], section: "quotation" },
      { key: "cargo_desc",        label: "Deskripsi Barang / Komoditi",              type: "textarea", required: true, placeholder: "Jenis barang, HS code, kondisi khusus, dll.", section: "quotation" },
      { key: "origin",            label: "Asal (Kota / Negara)",                     type: "text",    required: true, section: "quotation" },
      { key: "destination",       label: "Tujuan (Kota / Negara)",                   type: "text",    required: true, section: "quotation" },
      { key: "weight_volume",     label: "Berat / Volume",                           type: "text",    placeholder: "Contoh: 500 kg / 2 CBM", section: "quotation" },
      { key: "incoterms",         label: "Incoterms",                                type: "select",  options: ["EXW","FOB","CIF","DAP","DDP","FCA","Tidak ditentukan"], section: "quotation" },
      { key: "target_delivery_date", label: "Target Tanggal Pengiriman",             type: "date",                   section: "quotation" },
      { key: "customer_budget",   label: "Budget Customer (Rp / USD)",               type: "text",    placeholder: "Kosongkan jika tidak diketahui", section: "quotation" },
      { key: "special_req",       label: "Persyaratan Khusus dari Customer",         type: "textarea", placeholder: "Contoh: butuh insurance, dokumen tertentu, dll.", section: "quotation" },
      { key: "quote_deadline",    label: "Batas Waktu Penawaran dari Vendor",        type: "date",    required: true, section: "quotation" },
      { key: "vendor_phone",      label: "No. WhatsApp Vendor (untuk notifikasi otomatis)", type: "text", placeholder: "Contoh: 628123456789", section: "quotation" },
      { key: "notes_to_vendor",   label: "Pesan / Instruksi ke Vendor",              type: "textarea", placeholder: "Tambahan informasi yang perlu diketahui vendor", section: "quotation" },
    ],
    requiredDocuments: [],
    checklist: [],
    conditionalRules: [],
    validationRules: [
      { fieldKey: "customer_name",  message: "Nama Customer / Perusahaan wajib diisi"    },
      { fieldKey: "service_needed", message: "Layanan yang Dibutuhkan wajib dipilih"     },
      { fieldKey: "cargo_desc",     message: "Deskripsi Barang / Komoditi wajib diisi"   },
      { fieldKey: "origin",         message: "Asal wajib diisi"                          },
      { fieldKey: "destination",    message: "Tujuan wajib diisi"                        },
      { fieldKey: "quote_deadline", message: "Batas Waktu Penawaran dari Vendor wajib diisi" },
    ],
  },
};
