// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/VendorResponseForm.tsx": () => import("../components/mockups/VendorResponseForm.tsx"),
  "./components/mockups/sport-center-variants/Accessibility.tsx": () => import("../components/mockups/sport-center-variants/Accessibility.tsx"),
  "./components/mockups/sport-center-variants/Hierarchy.tsx": () => import("../components/mockups/sport-center-variants/Hierarchy.tsx"),
  "./components/mockups/sport-center-variants/Interaction.tsx": () => import("../components/mockups/sport-center-variants/Interaction.tsx")
};
