import {
  pgTable,
  serial,
  text,
  numeric,
  integer,
  jsonb,
  timestamp,
  boolean,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { suppliersTable } from "./suppliers";
import { companiesTable } from "./companies";

export const airFreightOrdersTable = pgTable("air_freight_orders", {
  id: serial("id").primaryKey(),
  orderNumber: text("order_number").notNull().unique(),
  companyId: integer("company_id").references(() => companiesTable.id, { onDelete: "set null" }),
  customerName: text("customer_name").notNull(),
  customerEmail: text("customer_email"),
  customerPhone: text("customer_phone"),
  customerCompany: text("customer_company"),
  originAirport: text("origin_airport").notNull(),
  destAirport: text("dest_airport").notNull(),
  tradeType: text("trade_type").notNull().default("export"),
  cargoType: text("cargo_type").notNull().default("general"),
  commodity: text("commodity"),
  pieces: integer("pieces"),
  packingType: text("packing_type"),
  grossWeight: numeric("gross_weight", { precision: 12, scale: 3 }),
  volumetricWeight: numeric("volumetric_weight", { precision: 12, scale: 3 }),
  chargeableWeight: numeric("chargeable_weight", { precision: 12, scale: 3 }),
  volumeCbm: numeric("volume_cbm", { precision: 12, scale: 3 }),
  incoterm: text("incoterm"),
  etdRequested: text("etd_requested"),
  additionalServices: text("additional_services").array(),
  specialInstructions: text("special_instructions"),
  notes: text("notes"),
  estimatedPrice: numeric("estimated_price", { precision: 14, scale: 2 }),
  selectedRfqSubmissionId: integer("selected_rfq_submission_id"),
  finalRatePerKg: numeric("final_rate_per_kg", { precision: 12, scale: 2 }),
  fuelSurcharge: numeric("fuel_surcharge", { precision: 12, scale: 2 }),
  securitySurcharge: numeric("security_surcharge", { precision: 12, scale: 2 }),
  awbFee: numeric("awb_fee", { precision: 12, scale: 2 }),
  handlingFee: numeric("handling_fee", { precision: 12, scale: 2 }),
  xrayFee: numeric("xray_fee", { precision: 12, scale: 2 }),
  docFee: numeric("doc_fee", { precision: 12, scale: 2 }),
  customsClearanceFee: numeric("customs_clearance_fee", { precision: 12, scale: 2 }),
  pickupTrucking: numeric("pickup_trucking", { precision: 12, scale: 2 }),
  deliveryTrucking: numeric("delivery_trucking", { precision: 12, scale: 2 }),
  cargoSurcharge: numeric("cargo_surcharge", { precision: 12, scale: 2 }),
  markupAmount: numeric("markup_amount", { precision: 12, scale: 2 }),
  ppnPct: numeric("ppn_pct", { precision: 5, scale: 2 }).default("11"),
  ppnAmount: numeric("ppn_amount", { precision: 14, scale: 2 }),
  subtotal: numeric("subtotal", { precision: 14, scale: 2 }).default("0"),
  grandTotal: numeric("grand_total", { precision: 14, scale: 2 }).default("0"),
  airline: text("airline"),
  flightNumber: text("flight_number"),
  etd: text("etd"),
  eta: text("eta"),
  transitDays: integer("transit_days"),
  awbNumber: text("awb_number"),
  trackingNotes: text("tracking_notes"),
  status: text("status").notNull().default("inquiry"),
  adminQuoteAttachmentUrl: text("admin_quote_attachment_url"),
  quoteToken: text("quote_token").unique(),
  quoteSentAt: timestamp("quote_sent_at", { withTimezone: true }),
  bookingConfirmedAt: timestamp("booking_confirmed_at", { withTimezone: true }),
  approvedVendorId: integer("approved_vendor_id").references(() => suppliersTable.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  companyStatusIdx: index("afr_orders_company_status_idx").on(t.companyId, t.status),
  statusIdx: index("afr_orders_status_idx").on(t.status),
}));

export const airFreightDimensionsTable = pgTable("air_freight_dimensions", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => airFreightOrdersTable.id, { onDelete: "cascade" }),
  length: numeric("length", { precision: 10, scale: 2 }),
  width: numeric("width", { precision: 10, scale: 2 }),
  height: numeric("height", { precision: 10, scale: 2 }),
  pieces: integer("pieces").default(1),
  grossWeight: numeric("gross_weight", { precision: 10, scale: 3 }),
  volumetricWeight: numeric("volumetric_weight", { precision: 10, scale: 3 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  orderIdx: index("afr_dimensions_order_idx").on(t.orderId),
}));

export const airFreightRfqsTable = pgTable("air_freight_rfqs", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => airFreightOrdersTable.id, { onDelete: "cascade" }),
  rfqNumber: text("rfq_number").notNull().unique(),
  blastVendorIds: integer("blast_vendor_ids").array(),
  blastCount: integer("blast_count").default(0),
  responseDeadline: timestamp("response_deadline", { withTimezone: true }),
  status: text("status").notNull().default("open"),
  blastNotes: text("blast_notes"),
  blastAt: timestamp("blast_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  orderIdx: index("afr_rfqs_order_idx").on(t.orderId),
}));

export const airFreightRateSubmissionsTable = pgTable("air_freight_rate_submissions", {
  id: serial("id").primaryKey(),
  rfqId: integer("rfq_id").notNull().references(() => airFreightRfqsTable.id, { onDelete: "cascade" }),
  orderId: integer("order_id").notNull().references(() => airFreightOrdersTable.id, { onDelete: "cascade" }),
  vendorId: integer("vendor_id").references(() => suppliersTable.id, { onDelete: "set null" }),
  vendorName: text("vendor_name"),
  token: text("token").notNull().unique(),
  airline: text("airline"),
  flightNumber: text("flight_number"),
  etd: text("etd"),
  eta: text("eta"),
  transitDays: integer("transit_days"),
  isDirect: boolean("is_direct").default(true),
  currency: text("currency").default("IDR"),
  exchangeRate: numeric("exchange_rate", { precision: 12, scale: 4 }).default("1"),
  ratePerKg: numeric("rate_per_kg", { precision: 12, scale: 2 }),
  weightBreakRates: jsonb("weight_break_rates"),
  fuelSurcharge: numeric("fuel_surcharge", { precision: 12, scale: 2 }).default("0"),
  securitySurcharge: numeric("security_surcharge", { precision: 12, scale: 2 }).default("0"),
  awbFee: numeric("awb_fee", { precision: 12, scale: 2 }).default("0"),
  handlingFee: numeric("handling_fee", { precision: 12, scale: 2 }).default("0"),
  xrayFee: numeric("xray_fee", { precision: 12, scale: 2 }).default("0"),
  docFee: numeric("doc_fee", { precision: 12, scale: 2 }).default("0"),
  customsClearanceFee: numeric("customs_clearance_fee", { precision: 12, scale: 2 }).default("0"),
  pickupTrucking: numeric("pickup_trucking", { precision: 12, scale: 2 }).default("0"),
  deliveryTrucking: numeric("delivery_trucking", { precision: 12, scale: 2 }).default("0"),
  cargoSurcharge: numeric("cargo_surcharge", { precision: 12, scale: 2 }).default("0"),
  otherFees: jsonb("other_fees"),
  totalIDR: numeric("total_idr", { precision: 14, scale: 2 }),
  validityDate: text("validity_date"),
  notes: text("notes"),
  attachmentUrl: text("attachment_url"),
  status: text("status").notNull().default("pending"),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  submitterIp: text("submitter_ip"),
  formOpenedAt: timestamp("form_opened_at", { withTimezone: true }),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  rfqIdx: index("afr_submissions_rfq_idx").on(t.rfqId),
  orderIdx: index("afr_submissions_order_idx").on(t.orderId),
}));

export type AirFreightOrder = typeof airFreightOrdersTable.$inferSelect;
export type InsertAirFreightOrder = typeof airFreightOrdersTable.$inferInsert;
export type AirFreightRfq = typeof airFreightRfqsTable.$inferSelect;
export type AirFreightRateSubmission = typeof airFreightRateSubmissionsTable.$inferSelect;
