import {
  pgTable, serial, text, numeric, integer, jsonb,
  timestamp, boolean, index,
} from "drizzle-orm/pg-core";
import { suppliersTable } from "./suppliers";
import { companiesTable } from "./companies";

export const oceanFreightRatesTable = pgTable("ocean_freight_rates", {
  id: serial("id").primaryKey(),
  rateCode: text("rate_code"),
  rateSourceType: text("rate_source_type").notNull().default("shipping_line"),
  rateSourceName: text("rate_source_name").notNull().default(""),
  vendorId: integer("vendor_id").references(() => suppliersTable.id, { onDelete: "set null" }),
  carrierName: text("carrier_name"),
  originCity: text("origin_city").notNull().default(""),
  originPort: text("origin_port").notNull().default(""),
  destinationCity: text("destination_city").notNull().default(""),
  destinationPort: text("destination_port").notNull().default(""),
  tradeType: text("trade_type").notNull().default("export"),
  shipmentType: text("shipment_type").notNull().default("FCL"),
  serviceMode: text("service_mode").notNull().default("port_to_port"),
  containerType: text("container_type"),
  currency: text("currency").notNull().default("USD"),
  exchangeRateToIdr: numeric("exchange_rate_to_idr", { precision: 15, scale: 4 }).default("16500"),
  oceanFreightAmount: numeric("ocean_freight_amount", { precision: 15, scale: 2 }).default("0"),
  lclRatePerCbm: numeric("lcl_rate_per_cbm", { precision: 15, scale: 2 }),
  lclMinimumCbm: numeric("lcl_minimum_cbm", { precision: 10, scale: 2 }),
  thcOrigin: numeric("thc_origin", { precision: 12, scale: 2 }).default("0"),
  thcDestination: numeric("thc_destination", { precision: 12, scale: 2 }).default("0"),
  docFee: numeric("doc_fee", { precision: 12, scale: 2 }).default("0"),
  blFee: numeric("bl_fee", { precision: 12, scale: 2 }).default("0"),
  doFee: numeric("do_fee", { precision: 12, scale: 2 }).default("0"),
  handlingFee: numeric("handling_fee", { precision: 12, scale: 2 }).default("0"),
  customsClearanceFee: numeric("customs_clearance_fee", { precision: 12, scale: 2 }).default("0"),
  truckingPickupEstimate: numeric("trucking_pickup_estimate", { precision: 12, scale: 2 }).default("0"),
  truckingDeliveryEstimate: numeric("trucking_delivery_estimate", { precision: 12, scale: 2 }).default("0"),
  insurancePercent: numeric("insurance_percent", { precision: 8, scale: 4 }).default("0"),
  dgSurchargePercent: numeric("dg_surcharge_percent", { precision: 8, scale: 4 }).default("0"),
  reeferSurcharge: numeric("reefer_surcharge", { precision: 12, scale: 2 }).default("0"),
  peakSeasonSurcharge: numeric("peak_season_surcharge", { precision: 12, scale: 2 }).default("0"),
  emergencyBunkerSurcharge: numeric("emergency_bunker_surcharge", { precision: 12, scale: 2 }).default("0"),
  currencyAdjustmentFactor: numeric("currency_adjustment_factor", { precision: 12, scale: 2 }).default("0"),
  validFrom: text("valid_from").notNull(),
  validUntil: text("valid_until").notNull(),
  transitDays: integer("transit_days"),
  carrier: text("carrier"),
  vesselName: text("vessel_name"),
  voyage: text("voyage"),
  directOrTransshipment: text("direct_or_transshipment").notNull().default("direct"),
  priceStatus: text("price_status").notNull().default("estimate"),
  notes: text("notes"),
  isActive: boolean("is_active").notNull().default(true),
  companyId: integer("company_id").references(() => companiesTable.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  routeIdx: index("ofr_rates_route_idx").on(t.originPort, t.destinationPort, t.shipmentType),
  activeIdx: index("ofr_rates_active_idx").on(t.isActive, t.validFrom, t.validUntil),
}));

export const oceanFreightOrdersTable = pgTable("ocean_freight_orders", {
  id: serial("id").primaryKey(),
  orderNumber: text("order_number").notNull().unique(),
  companyId: integer("company_id").references(() => companiesTable.id, { onDelete: "set null" }),
  customerId: integer("customer_id"),
  customerName: text("customer_name").notNull().default(""),
  customerPhone: text("customer_phone"),
  customerEmail: text("customer_email"),
  customerCompany: text("customer_company"),
  originCity: text("origin_city").notNull().default(""),
  originPort: text("origin_port").notNull().default(""),
  destinationCity: text("destination_city").notNull().default(""),
  destinationPort: text("destination_port").notNull().default(""),
  tradeType: text("trade_type").notNull().default("export"),
  serviceMode: text("service_mode").notNull().default("port_to_port"),
  shipmentType: text("shipment_type").notNull().default("FCL"),
  containerType: text("container_type"),
  containerQty: integer("container_qty"),
  totalCbm: numeric("total_cbm", { precision: 12, scale: 3 }),
  grossWeight: numeric("gross_weight", { precision: 12, scale: 3 }),
  koli: integer("koli"),
  commodity: text("commodity").notNull().default("General Cargo"),
  hsCode: text("hs_code"),
  cargoValue: numeric("cargo_value", { precision: 14, scale: 2 }),
  cargoCondition: text("cargo_condition").notNull().default("general"),
  incoterm: text("incoterm"),
  etdPreferred: text("etd_preferred"),
  etaTarget: text("eta_target"),
  selectedAdditionalServices: jsonb("selected_additional_services"),
  selectedEstimateOption: text("selected_estimate_option"),
  estimatedPrice: numeric("estimated_price", { precision: 14, scale: 2 }),
  estimatedPriceIdr: numeric("estimated_price_idr", { precision: 14, scale: 2 }),
  currency: text("currency").default("IDR"),
  pricingBreakdown: jsonb("pricing_breakdown"),
  selectedRateId: integer("selected_rate_id"),
  candidateRateIds: jsonb("candidate_rate_ids"),
  finalRateId: integer("final_rate_id"),
  finalPrice: numeric("final_price", { precision: 14, scale: 2 }),
  finalPriceIdr: numeric("final_price_idr", { precision: 14, scale: 2 }),
  markupAmount: numeric("markup_amount", { precision: 14, scale: 2 }),
  ppnAmount: numeric("ppn_amount", { precision: 14, scale: 2 }),
  grandTotal: numeric("grand_total", { precision: 14, scale: 2 }),
  finalBreakdown: jsonb("final_breakdown"),
  adminNotes: text("admin_notes"),
  customerNotes: text("customer_notes"),
  priceStatus: text("price_status").notNull().default("estimate"),
  status: text("status").notNull().default("waiting_rate"),
  source: text("source").notNull().default("customer_portal"),
  // Booking fields
  bookingNumber: text("booking_number"),
  carrier: text("carrier"),
  vesselName: text("vessel_name"),
  voyage: text("voyage"),
  etd: text("etd"),
  eta: text("eta"),
  pol: text("pol"),
  pod: text("pod"),
  containerNumber: text("container_number"),
  sealNumber: text("seal_number"),
  blNumber: text("bl_number"),
  bookingConfirmationUrl: text("booking_confirmation_url"),
  adminQuoteAttachmentUrl: text("admin_quote_attachment_url"),
  // Quote flow
  quoteToken: text("quote_token").unique(),
  quoteSentAt: timestamp("quote_sent_at", { withTimezone: true }),
  bookingConfirmedAt: timestamp("booking_confirmed_at", { withTimezone: true }),
  // Tracking status (post-booking)
  trackingStatus: text("tracking_status"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  statusIdx: index("ofo_orders_status_idx").on(t.status),
  companyIdx: index("ofo_orders_company_idx").on(t.companyId, t.status),
}));

export const oceanFreightRfqsTable = pgTable("ocean_freight_rfqs", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => oceanFreightOrdersTable.id, { onDelete: "cascade" }),
  rfqNumber: text("rfq_number").notNull().unique(),
  blastVendorIds: integer("blast_vendor_ids").array(),
  blastCount: integer("blast_count").default(0),
  responseDeadline: timestamp("response_deadline", { withTimezone: true }),
  status: text("status").notNull().default("open"),
  blastNotes: text("blast_notes"),
  blastAt: timestamp("blast_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  orderIdx: index("ofo_rfqs_order_idx").on(t.orderId),
}));

export const oceanFreightRateSubmissionsTable = pgTable("ocean_freight_rate_submissions", {
  id: serial("id").primaryKey(),
  rfqId: integer("rfq_id").notNull().references(() => oceanFreightRfqsTable.id, { onDelete: "cascade" }),
  orderId: integer("order_id").notNull().references(() => oceanFreightOrdersTable.id, { onDelete: "cascade" }),
  vendorId: integer("vendor_id").references(() => suppliersTable.id, { onDelete: "set null" }),
  vendorName: text("vendor_name"),
  token: text("token").notNull().unique(),
  rateSourceType: text("rate_source_type").default("forwarder_partner"),
  rateSourceName: text("rate_source_name"),
  carrier: text("carrier"),
  oceanFreightAmount: numeric("ocean_freight_amount", { precision: 15, scale: 2 }),
  currency: text("currency").default("USD"),
  exchangeRate: numeric("exchange_rate", { precision: 12, scale: 4 }).default("16500"),
  validityDate: text("validity_date"),
  vesselName: text("vessel_name"),
  voyage: text("voyage"),
  etd: text("etd"),
  eta: text("eta"),
  transitDays: integer("transit_days"),
  directOrTransshipment: text("direct_or_transshipment").default("direct"),
  thcOrigin: numeric("thc_origin", { precision: 12, scale: 2 }).default("0"),
  thcDestination: numeric("thc_destination", { precision: 12, scale: 2 }).default("0"),
  docFee: numeric("doc_fee", { precision: 12, scale: 2 }).default("0"),
  blFee: numeric("bl_fee", { precision: 12, scale: 2 }).default("0"),
  doFee: numeric("do_fee", { precision: 12, scale: 2 }).default("0"),
  handlingFee: numeric("handling_fee", { precision: 12, scale: 2 }).default("0"),
  truckingPickup: numeric("trucking_pickup", { precision: 12, scale: 2 }).default("0"),
  truckingDelivery: numeric("trucking_delivery", { precision: 12, scale: 2 }).default("0"),
  customsClearanceFee: numeric("customs_clearance_fee", { precision: 12, scale: 2 }).default("0"),
  surchargeAmount: numeric("surcharge_amount", { precision: 12, scale: 2 }).default("0"),
  notes: text("notes"),
  attachmentUrl: text("attachment_url"),
  totalAmount: numeric("total_amount", { precision: 14, scale: 2 }),
  totalAmountIdr: numeric("total_amount_idr", { precision: 14, scale: 2 }),
  status: text("status").notNull().default("pending"),
  isActive: boolean("is_active").default(true).notNull(),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  formOpenedAt: timestamp("form_opened_at", { withTimezone: true }),
  submitterIp: text("submitter_ip"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  rfqIdx: index("ofo_submissions_rfq_idx").on(t.rfqId),
  orderIdx: index("ofo_submissions_order_idx").on(t.orderId),
}));

export type OceanFreightRate = typeof oceanFreightRatesTable.$inferSelect;
export type InsertOceanFreightRate = typeof oceanFreightRatesTable.$inferInsert;
export type OceanFreightOrder = typeof oceanFreightOrdersTable.$inferSelect;
export type InsertOceanFreightOrder = typeof oceanFreightOrdersTable.$inferInsert;
export type OceanFreightRfq = typeof oceanFreightRfqsTable.$inferSelect;
export type OceanFreightRateSubmission = typeof oceanFreightRateSubmissionsTable.$inferSelect;
