import {
  pgTable,
  serial,
  text,
  numeric,
  boolean,
  jsonb,
  timestamp,
  integer,
} from "drizzle-orm/pg-core";

export const quotationReplyLogsTable = pgTable("quotation_reply_logs", {
  id: serial("id").primaryKey(),
  rfqId: text("rfq_id"),
  orderId: integer("order_id"),
  customerName: text("customer_name").notNull(),
  customerPhone: text("customer_phone").notNull(),
  vendorName: text("vendor_name"),
  vendorPhone: text("vendor_phone"),
  serviceType: text("service_type"),
  route: text("route"),
  vendorPrice: numeric("vendor_price", { precision: 14, scale: 2 }),
  markupType: text("markup_type").notNull().default("percentage"),
  markupValue: numeric("markup_value", { precision: 14, scale: 2 }).notNull().default("0"),
  finalPrice: numeric("final_price", { precision: 14, scale: 2 }).notNull(),
  pickupDate: text("pickup_date"),
  deliveryDate: text("delivery_date"),
  notes: text("notes"),
  status: text("status").notNull().default("Ready"),
  messageBody: text("message_body").notNull(),
  fonnteResponse: jsonb("fonnte_response"),
  sentStatus: text("sent_status").notNull().default("draft"),
  sentToAdmin: boolean("sent_to_admin").default(false),
  sentAt: timestamp("sent_at"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
